### ISSUE TITLE
[FEATURE] Support for Thermostats

### ISSUE THREAD

**Issue by powermarcel10** [mennovanhout/flutter-hdashboards-issues#10]
I would like to see support for thermostats and airco's. I added a image file as an idea of how it should look like. But that is up to you off course! 😃

This is how to default thermostat card of Home Assistant looks like:

![thermostat_card](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/2340835/2bbbc57a-b790-4eb0-91c3-9b07980c6fcb)
/

**Comment by roko14** [comment]
I can't handle my e-thermostat (Google Nest) at all. Only the temperature is displayed.

**Comment by powermarcel10** [comment]
Thermostats are not jet supported.. So, we just have to wait.

**Comment by mennovanhout** [comment]
Will work on it soon!!! have been busy with supporting homey pro 2019 / 2016
