### ISSUE TITLE
[FEATURE] Make it easier to identify devices in the device list

### ISSUE THREAD

**Issue by marium0505** [mennovanhout/flutter-hdashboards-issues#100]
Would it be possible to make it possible to filter by, or at least see the room/zones of the devices in the device list? 

It would make it a lot easier to identify devices (which gets harder when you have a lot of devices). 

And if it's possible to add multiple homes (I haven't looked into it yet as I'm currently still working on the dashboard for the first home I added, and don't want to risk making that harder by adding a new one): please add name of Homey to the device, and/or make it possible to filter by Homey. Actually, name of Homey can with benefit be added anyways. 

One way to do it is something like this
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/1466933/671a8f69-a533-4305-b1a0-2b1f6bb56e4e)

While filtering by room/Homey Name would be gold, adding the names there is an alright compromise, until you find a good way to add filtering/sorting.

**Comment by mennovanhout** [comment]
Added v0.3.3 will contain zone name
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/174c3a59-0e8a-4898-9f11-868f32ff2638)
