### ISSUE TITLE
[BUG] Web version no color icons

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#102]
**Describe the bug**
When added a VD by DC than the icon in shown in text field are in color on Android but not in web

**Expected behavior**
Also colored icons on web

**Screenshots**
Web
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/b9c59f07-2e82-49fb-bd90-a074305af1a4)
Android
![SmartSelect_20231126_111414](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/48a79dcb-89c2-4a5c-82e7-69b4183af214)

**Using information (please complete the following information):**
 - OS: [Android, Windows]
 - Browser [Chrome]
 - Version [e.g. Android app v0.3.2+15, web version v0.3.2+15]

**Comment by mennovanhout** [comment]
Tweaked the web renderen in v0.3.3 I hope it works in this case, if not the renderer might not be able to do it.
