### ISSUE TITLE
Setting buttons in Homey should not appear as button in a tile.

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#103]
Some Homey Devices (in my case Shelly pro) do have buttons in the settings screen in Homey. The button should not apear in the HD tile at leased not when during creation of the tile “no controls” is selected. Maybe not at all.

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_9472](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/39216786/60cea5bf-263f-4020-8008-2c51936ef5e2)
![IMG_9473](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/39216786/857578ad-dd25-4c1c-8507-158ca67b4f45)
![IMG_9475](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/39216786/07e5d267-c631-4716-9928-615759fc3118)
![IMG_9474](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/39216786/7eeb36c6-cbbb-40b0-9e63-3a7ad4b1e583)

**Using information (please complete the following information):**
 - OS: IOS and Web
 - Browser: chrome
 - Version 0.3.2

**Homey device**
 - Device: HP2023

**Additional context**

**Comment by MP-ICT-Diensten** [comment]
I see that to, in Homey the screen with Power button (on/off) is the first screen, additional buttons are on the second screen. In HDashboard the powerbutton is also showed on the button screen with an Advanced Device I made.

**Comment by mennovanhout** [comment]
Removed it for no controls in next update!
