### ISSUE TITLE
[BUG] On/Off Button duplicated as Push

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#104]
**Describe the bug**
When i have 2 on/off buttons in a VD made by DC with a class button than the second button is duplicated as a push button.
So i see the on/off and the push, but the push is wrong

**Expected behavior**
See what kind of buttons it are and sort them in the correct tab

**Screenshots**
This are the on/off buttons
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/cbea63f1-efca-4993-9d70-3d8e843eaa54)
This are the push buttons that don't exist
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/731454a4-4e75-4439-a0a9-82bc5ef858de)
This is the setting of the buttons
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/c58f4b3e-b62c-4890-9537-87eaddccd319)

**Using information (please complete the following information):**
 - OS: [Android, Windows]
 - Browser [Chrome]
 - Version [Android app v0.3.2+15, web version v0.3.2+15]

**Homey device**
 - Device: [Homey pro 2023]

**Comment by mennovanhout** [comment]
Fixed in v0.4.4
