### ISSUE TITLE
[FEATURE] Text scrolling multi tile

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#105]
**Describe the bug**
When the text is to long and you make the tile larger than the text still keep scrolling

**Expected behavior**
when tile is bigger and theirs space don't let the text scrol

**Screenshots**
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/f4fcaf88-d6a9-402a-b7c9-7b178583106d)

**Comment by ericvanscheers** [comment]
Same issue here

**Comment by mennovanhout** [comment]
Upgared to feature, works as designed. But better use of space is a great idea

**Comment by StaffordBully** [comment]
Hope it will be soon.  I've a lot of scrolling text. Would be nice to actually see the whole text

**Comment by mennovanhout** [comment]
> Hope it will be soon. I've a lot of scrolling text. Would be nice to actually see the whole text

No pressure at all lol....
