### ISSUE TITLE
[FEATURE] Label not visible multi tile

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#106]
**Is your feature request related to a problem? Please describe.**
The label itself isn't visible in the multi tile. i use it to update the last changes on the device.

**Describe the solution you'd like**
An option to show label or not

**Describe alternatives you've considered**
like i have it now
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/e77050d4-3a45-46bd-b24b-fe930b15d0d4)
like i see it in the multi tile
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/0dbe4fc9-69dc-40d7-9f2f-eb06d01da12e)

**Comment by StaffordBully** [comment]
Maybe the label like this?
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/169bb142-9c15-49c8-afe1-ede51d071362)

**Comment by mennovanhout** [comment]
Added in v0.4.4
