### ISSUE TITLE
[FEATURE] Change position device multi tile

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#107]
**Is your feature request related to a problem? Please describe.**
when you have a few devices in the multi tile and you wan't to change the order of it, you need to remove them all

**Describe the solution you'd like**
a way to change the position, for example you have 6 devices and you can place device 6 to place 2
**Describe alternatives you've considered**

**Comment by jeesnl** [comment]
This is a must have.

**Comment by ronennieshow** [comment]
Also it would be nice to be have the option to edit an value in the multi tile in stead of making a new

**Comment by mennovanhout** [comment]
Done in v0.4.5
