### ISSUE TITLE
Description of Multi tile should be vertical instead of horizontal

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#112]
When you select add->layout there is an option to select Multicard (Horizontal).
The description of Horizontal should be Vertical.

To me it's more logical to have the Multicard in the first selection screen.

**Comment by MP-ICT-Diensten** [comment]
I would say, depending on the size of the multi tile, in normal Latin order, left to right and then one down. In case of a non latin dashboard, it can be right  to left an then down, or even left up, down and the one to right. To be really multi language :)

Maybe the multi column is the best option.

**Comment by mennovanhout** [comment]
Renamed it to just Multicard in v0.4.2
