### ISSUE TITLE
[BUG] Clock seconds counter, distorsion on screen iOS app.

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#113]
Digital clock seconds counter shows distorsion on the dashboard. Using the iOS app, currently the 0.4, but it was there in previous versions as well.

Video will follow later, seems not te be able to add it from iPad.

**Comment by mennovanhout** [comment]
So this is on iPhone or only iPad? just to confirm?

**Comment by MP-ICT-Diensten** [comment]
This is on an iPad, I don't have an iPhone.  If I make sure that there are no tiles with scrolling text, then it is disappeared. So it is  a combination of the digital clock with seconds and at least one tile with scrolling text.

**Comment by mennovanhout** [comment]
thanks I will look into this!

**Comment by mennovanhout** [comment]
Little update:
- Sorry that particulair ipad updates take longer to fix, this is because I can't code right now on my macmini and can't run an ipad emulator in windows...... 

Will still be solved soon :3

**Comment by mennovanhout** [comment]
This is the real app right, not web? i just installed ipad emulators to figure it out!

**Comment by MP-ICT-Diensten** [comment]
Real app and still exist, digital clock with tile with scrolling text.

**Comment by MP-ICT-Diensten** [comment]
With 4.5 +22 it is still there

**Comment by mennovanhout** [comment]
Yes no fix yet, but i Bought an ipad to run better ipad only tests

**Comment by mennovanhout** [comment]
Should be resolved with latests performance updates, please let me know if it still occurs.
