### ISSUE TITLE
Multi tile

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#114]
Allereerst heel blij met multi tile!
Bij de nieuwe functie multi tile zie je bij een deursensor, open contact een vinkje en bij een dicht contact een rood kruis. In mijn beleving is dit logischer andersom.
Deur dicht is een vinkje deur open een rood kruis.
Als voorbeeld: we gaan van huis en dan ik kijk of alle deuren en ramen gesloten zijn, een rood kruis wekt dan extra aandacht op….. 
Een vinkje duidt erop dat alles goed is.

**Describe the solution you'd like**
Vinkje als deur/raam dicht is en rood kruis bij open.

**Comment by StaffordBully** [comment]
Deze logica is juist contact alarm = vinkje, geen alarm = kruisje.
Als je liever andersom wilt can je instellingen van je contact niet wijzigen? van normaal gesloten naar normaal open dan zijn je vinkjes lijk je wilt maar is de logica weg :p

**Comment by ronaldsomers** [comment]
Daar valt over te twisten 😉
In mijn beleving zoals bij Homey en het dashboard van homeycornelissen.
Tegel is rood als deur open staat.
Deur open zie een oranje cirkeltje met een ! Of Rode tegel, (contact)alarm is gevaar.

![IMG_1669](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/e9c0f70c-869c-4798-b478-73caec87d801)


![IMG_1668](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/e2ee6aad-e9eb-42b7-92c8-a6e48baaa610)

**Comment by StaffordBully** [comment]
Het is inderdaad hoe je het bekijkt en iedereen maakt het anders.
Kunt wel zeggen voor het overzichtelijk te houden en geen verwarring alarm is uitroepteken geen alarm geen tekens, dan is het hetzelfde als in homey en ervoor was op Hdashboards.
Nu is het ook alarm tegel oranje geen alarm niks

**Comment by StaffordBully** [comment]
Als je het helemaal naar eigen smaakt wilt hebben maak je zelf je virtuele apparaten en kan je zelfs tekst zien open/dicht.

**Comment by ronaldsomers** [comment]
> Het is inderdaad hoe je het bekijkt en iedereen maakt het anders. Kunt wel zeggen voor het overzichtelijk te houden en geen verwarring alarm is uitroepteken geen alarm geen tekens, dan is het hetzelfde als in homey en ervoor was op Hdashboards. Nu is het ook alarm tegel oranje geen alarm niks

Bedankt voor het meedenken.
Op de foto 2 deuren die dicht zijn, dan verwacht ik geen rood kruis.

![IMG_1670](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/ccb2b6d5-655d-4737-a99d-e48e798340a0)

**Comment by ronaldsomers** [comment]
> Als je het helemaal naar eigen smaakt wilt hebben maak je zelf je virtuele apparaten en kan je zelfs tekst zien open/dicht.

Dat is inderdaad ook een overweging.
Dan krijg ik wel veel devices erbij en overzicht wil ik ook houden.
Ga ‘t wellicht uitproberen.
Thanks

**Comment by StaffordBully** [comment]
snap je ook, maar misschien dat menno er nog iets van kan maken.
Nu zie je voordeur x maar eigenlijk is het de sensor die zegt geen alarm.
Dus beter zou zijn als mijn voorbeeld hieronder 
![287449511-ccb2b6d5-655d-4737-a99d-e48e798340a0](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/70901a37-7010-4987-b72c-0542226dc02e)

**Comment by StaffordBully** [comment]
Hij zal er wel iets mee doen, heeft nu veel leeswerk en moet nog heel wat aangepast worden, volgende update zal zeker veel verbeteringen bieden, nog even geduld hebben ;)

**Comment by ronaldsomers** [comment]
> Hij zal er wel iets mee doen, heeft nu veel leeswerk en moet nog heel wat aangepast worden, volgende update zal zeker veel verbeteringen bieden, nog even geduld hebben ;)

Zeker alle vertrouwen in!
Het werkt met de losse tegels al goed.
Goed weekend!

**Comment by mennovanhout** [comment]
From update v0.4.2 it will be the same as normal tiles!
