### ISSUE TITLE
[BUG] Scrolling multicard

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#116]
**Describe the bug**
When you have a few multicards for example on your phone and they are big enough and you will scroll down the page you must place your finger between to multicards what is small otherwise you can't scroll

**Expected behavior**
when end of scoll in multicard of no scoll because big enough than col the page?

**Comment by jeesnl** [comment]
Correct, when the multi card is big enough for the tiles entered, avoid scrolling of the multi card.

**Comment by mennovanhout** [comment]
Should be better in v0.4.2
