### ISSUE TITLE
[BUG] Multicard icons switches

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#118]
**Describe the bug**
When i add my switches to the multicard the on/off button colors by status but the icon stay grey

**Expected behavior**
Icon color by status like normal tiles and other lights

**Screenshots**
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/69908063-12d2-4dbe-b80a-15df93beccaa)

**Comment by mennovanhout** [comment]
Done in v0.4.2
