### ISSUE TITLE
Dag/nacht modus

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#119]
Dag/nacht modus is verplaatst naar Settings in menu.
Het was wel erg makkelijk om dat vanuit het dashboard zelf te doen.
Ik gebruik het erg veel bij maken van dashboards.
De kolommen zijn beter zichtbaar in dagmodus.
Graag icon weer terug plaatsen.😁

**Comment by MP-ICT-Diensten** [comment]
Deze is uitgevoerd, vanwege dit verzoek: https://github.com/mennovanhout/flutter-hdashboards-issues/issues/98

En de kolommen in dark mode zijn al beter, bij mij in ieder geval wel, maar mogelijk dat in edit mode de grid lijnen nog iets helderder kunnen.  Hiervoor bestaat issue: https://github.com/mennovanhout/flutter-hdashboards-issues/issues/75  wat uitgevoerd is en alweer gesloten.

**Comment by mennovanhout** [comment]
Closed for #98 
I did however make the lines brigher in darkmode!
