### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#120]
Rolluikpositie wordt in positie 100% weer gegeven als 1% in multi tile.
In een losse tegel wordt het goe weer gegeven.
iOS app
Rolluikschakelaar van Robbshop, eigen merk.

![IMG_1677](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/196d55ec-94d3-47d3-b610-0f872f9fc233)
![IMG_1679](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/51ac7793-7a62-46f1-92d0-6bde6489e992)

**Comment by MP-ICT-Diensten** [comment]
Tweede plaatje is niet duidelijk, texten zijn niet te zien.

Maar ik zie nog steeds mijn rolluik (shelly rollers)  op groen en 100% staan, die zouden toch op 0% dan moeten staan en rood?  want dat is reversed t.o.v. wat het was en nog steeds is bij mij.  Ik heb e al een paar keer verwijderd en weer toegevoegd, maar lijkt niet te werken in mijn setup.

**Comment by mennovanhout** [comment]
Fixed in v0.4.2, bedankt!
