### ISSUE TITLE
[BUG] Scrolling list is almost not possible

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#121]
**Describe the bug**
When a device has a scrolling list and you want to change a setting on the web it jumps quickly i tried 3 different devices.
Example, alarm has 3 settings but the middle one isn't possible to select on web bij scrolling the mouse, clicking doesn't work

**Expected behavior**
scroll more smoothly or click on the setting you need

**Screenshots**
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/3b1f91e9-2fdd-4b9b-808b-296c1882d674)

**Using information (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [Web version v0.4.1+18]

**Comment by mennovanhout** [comment]
Fixed in v0.4.4
The scrollwheel mallfunctioned to much so I rewrote this part in something simpler that works better
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/31708bb0-e06a-461e-a684-d81f10ecdff0)
