### ISSUE TITLE
[BUG] Card error multicard

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#124]
**Describe the bug**
When i try to add my homecinema to the multicard, it is not possible. as a single tile no problem

When i add the device
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/7131efe6-7f53-4386-882f-1aba85230daa)

Then i get the error
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/91963b30-8f14-4938-8d41-59720df1b9b8)

But when i want to select a label
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/2e965390-ff3c-4dbc-b79a-940396859752)

**Comment by mennovanhout** [comment]
Thats not a bug :3? not all devices have labels.
