### ISSUE TITLE
[FEATURE] Scrolling right, left

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#125]
**Is your feature request related to a problem? Please describe.**
scrolling the dashboard is now only possible up and down

**Describe the solution you'd like**
Would be nice if we can also right and left, if the tile is to smal you can make it wider.
on phones you can set more tiles next to each other instead only under each other

**Comment by mennovanhout** [comment]
I've looked into this but it's not that nice in use actually. It also comes with glitches and anoying fix when you wanna interact with sliders. it's really hard to make this work nicely.
