### ISSUE TITLE
[FEATURE] Multicard add second header

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#126]
**Is your feature request related to a problem? Please describe.**
if you have a lot of devices it's fun with the multicard, but an extra header option would be nice

**Describe the solution you'd like**
add a extra header (title) inside the multicard, then you can add more to one multicard, made an example. 
![Dubble title](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/b702059d-ef39-4d3d-9868-1d0561cf24ec)

**Comment by mennovanhout** [comment]
Good one
