### ISSUE TITLE
[FEATURE] device log

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#127]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to know when or who used the device,  in homey is a device log. That I'm missing here

**Describe the solution you'd like**
When long press also a tab with the device log

**Comment by mennovanhout** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/c03037a8-e23c-487a-a793-b524bf712096)
Added in upcoming version v0.4.4
