### ISSUE TITLE
[BUG] different behavior between card and multicard for VD with hidden On/Off button

### ISSUE THREAD

**Issue by pilpfiction** [mennovanhout/flutter-hdashboards-issues#134]
**Describe the bug**
I created a VD with a button "On/Off Hidden" and added this to HD as a single tile (card) and as multicard. I choosed to display a capability of type number (Dauer) in both options. This results basically displaying same information in a different way:
![Screenshot_20231214-141831](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/1f4861de-abd3-4ba0-a608-68c14d5344a4)

1. Bug
while I can set the VD on and off with the multicard option in HD, the single card only lets me set the VD on, but not off!!!

2. Bug
While creating the multicard I can choose the hidden button ("Betrieb") as capability, but I can't do that while adding a single card.

**To Reproduce**
1. Create a VD with a hidden On/Off button and number field (displayed as capability in HD)
4. Go-to HD
5. Add the VD as single card and as multicard
6. Click both devices and see that you can set the device off only with the multicard, not the single card

**Expected behavior**
Same behaviour in both scenarios!
Regarding the hidden button being listed in the capabilities list or not: don't know what is correct, but should be same in both cases!?

**Screenshots**
see below

**Using information (please complete the following information):**
 - OS: Android
 - Browser chrome
 - Version [e.g. Android app v0.44]

**Homey device**
 - Device: [e.g. Homey pro 2023]

**Additional context**
VD in Homey:
(Top: single card / Bottom: multicard)
![Screenshot_20231214-141856~2](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/e4b3cff8-34c7-4bdd-a3dd-d540b22980f8)

Adding VD as single card in HD:
(capabilities I can select - no button available!!!)
![Screenshot_20231214-142526](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/a50e1700-b01b-40f3-adac-c9a8df4a1780)

Adding VD as multicard in HD:
(hidden button "Betrieb" can be selected!!!)
![Screenshot_20231214-142552](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/49a37bb5-4918-4c08-a212-6d71bef0c0d8)

**Comment by pilpfiction** [comment]
The issue why off is not working on the single card as described in the incident above, is probably because the option 'show controls' was enabled.

When this option is disabled on/off is working as expected. Only when the option is enabled the off seems to be disabled.

**Comment by pilpfiction** [comment]
My experience while setting up a VD with buttons (more than one) give me the impression that the behaviour between homey and HD is very different. HD does not behave the same way as homey interacts with buttons.

I am afraid the above mentioned problem is just one of many issues. I guess a thoroughly testing with different scenarios are required in order to identify all issues. Fixing a single issue as mentioned above, will not lead to a solid solution.

In order to do this deeper knowledge on VD and it's concepts are required - this goes beyond my level of knowledge! 

In some circumstances it might be even correct how HD acts. But as the behavior is different to VD, it's hard for me to finally judge whether VD in homey or HD acts wrong.

**Comment by mennovanhout** [comment]
This is the best most detaield bug report i've ever seen!

**Comment by mennovanhout** [comment]
Fixed in v0.4.5

**Comment by pilpfiction** [comment]
I used to work as product manager in a software company, so I know how important it is to have a well described issue 😉
