### ISSUE TITLE
App sluit spontaan af.

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#135]
App v0.4.4+21 sluit spontaan af, eerst leek ‘t erop alleen tijdens bewerken maar op nu blijkt ook op de iPad die aan de muur heb hangen na de update spontaan af te sluiten.

 Device:Homey pro 2023
Op 2 verschillende iPads, op iPhone lijkt ‘t goed te gaan.
Webapp niet getest.

**Comment by ronaldsomers** [comment]
Ook op webapp probleem, start niet op.
![IMG_1693](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/ce143603-e1fd-48d6-b00b-ff8665cbbb1e)

**Comment by ronaldsomers** [comment]
Update, na reboot van Homey lijkt het weer goed te gaan.
Homey was pas een uurtje of 4 geleden nog gerevolteerd 🧐

**Comment by ronaldsomers** [comment]
Helaas Menno, app sluit toch weer spontaan af.

**Comment by mennovanhout** [comment]
Hey Ronald, Thanks voor de updates en excuses dat je dit helaas mee maakt!.
Kan je achterhalen of je homey nog problemen had?
Het enige wat me nu te binnen schiet, is dat de connectie uitvalt en er met herstel een crash plaats vind.
Sluit de app helemaal af, en je hebt geen logs?
Ik ga even kijken of ik wat kan zien op mijn iPad emulator.

**Comment by ronaldsomers** [comment]
> Hey Ronald, Thanks voor de updates en excuses dat je dit helaas mee maakt!. Kan je achterhalen of je homey nog problemen had? Het enige wat me nu te binnen schiet, is dat de connectie uitvalt en er met herstel een crash plaats vind. Sluit de app helemaal af, en je hebt geen logs? Ik ga even kijken of ik wat kan zien op mijn iPad emulator.

Idee heb ik ook dat connectie uitvalt, ik heb geen enkel probleem met homey en nu app weer spontaan uitvalt heb ik een ping open gezet naar homey en die geeft 0% verlies. Connectie op dat punt oke.
Ter info, homey is LAN connected.

**Comment by mennovanhout** [comment]
Potential fix in v0.4.5
