### ISSUE TITLE
[BUG] dim rgb lights visual

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#136]
**Describe the bug**
When longpress on rgb lights in dim tab  its almost impossible to see the dimlevel when rgb lights on white.

**Expected behavior**
Background from the slider a  grey tint so the dimlevel is visible when lights on white.

**Screenshots**
Dimlevel 100%
![Screenshot_20231214_185926.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/ef0b411e-91da-4a70-a3be-08ff6ebf97b3)

Dimlevel 50%
![Screenshot_20231214_185947.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/1a92484a-2c42-4917-94ca-14c86962b7f1)

**Comment by mennovanhout** [comment]
Solved in v0.4.5
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/9a264765-4fff-4dc7-9b28-d5f3dc05be76)
