### ISSUE TITLE
[BUG] Channel pushbuttons not available

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#139]
**Describe the bug**
I add in my device capabilities a channel up and channel down pushbutton.
Than i can set a timer for example turn on/of my airco.
I used this kind of button because the visual is better and is not just a button

**To Reproduce**
This are the settings of my device capabilities.
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/1d9980dd-0b27-46d4-a87e-c1ad6e16c546)

This is how its shown in homey
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/447a2223-d942-4ba2-8c58-1c9c2c410fd1)

so when i hit +1 the timer goes up by 1min when i hit -1 the timer goes down by 1 min
than i can change the timer what is perfect for me at the moment itself.

**Expected behavior**
Pushbuttons that added to pushbuttons tap with a visual up/down or +/-

**Screenshots**
This is an example how it could look, i prefer + and - than i could be used for a lot more an also for real channel buttons in feature
 ![1](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/7fcac586-2e73-4e82-9ce8-f6f8e41cfba6)
![2](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/eada16b5-a9df-40bd-bad9-0e72beb397cd)

**Comment by mennovanhout** [comment]
Fixed in upcoming update v0.5.1
