### ISSUE TITLE
[FEATURE] RGB color on/off button multicard

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#140]
**Is your feature request related to a problem? Please describe.**
Now when a RGB light is on, the icon of the tile changes to the color of the light but the on/off stays green like this
![rgb green](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/d3c8fba6-5b4a-4fdc-b6fa-520b8b477d5d)

**Describe the solution you'd like**
It would be visual nice to also change the on/off button color when the light is on, same as the icon, than we get this.
![rgb color](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/21b1cb3f-9fcc-4644-ae67-ad6393e6132b)

I think it's looking nice.

**Comment by mennovanhout** [comment]
Done in v0.5.2
