### ISSUE TITLE
[BUG] Yes/No field of VD not shown in multicard

### ISSUE THREAD

**Issue by pilpfiction** [mennovanhout/flutter-hdashboards-issues#141]
**Describe the bug**
The value of the Yes/No field of a VD (based on the app "Device Capabilities") is not shown in multicard.

On a longpress on this multicard, the Y/N field is displayed with its value (true or false), which means the value is availing HD, but just not displayed!

**To Reproduce**
1. Create a VD with a Y/N field
2. Go-to to HD
3. Add this field as capability in a multicard
4. To compare also create a single card with the device and this Y/N field as selected capability 

**Expected behavior**
The value (true or false) should be visible in the multicard.

**Screenshots**
Added capability in a multicard:
![Screenshot_20231217-142212~2](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/854b2dc4-48fe-40dd-b710-9c74cf7bfb9e)

Longpress on the above multicard:
![Screenshot_20231217-143035](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/29163413-2efc-458a-a3a3-7dacbdc825b8)

Same capability added in a single card:
![Screenshot_20231217-142155~2](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/aa1726c0-9345-4279-87b0-1a1ddb4fc56e)

**Using information (please complete the following information):**
 - OS: [e.g. iOS, Android]
 - Browser [e.g. chrome]
 - Version [e.g. Android app v0.44]

**Homey device**
 - Device: [e.g. Homey pro 2023]

**Additional context**

**Comment by mennovanhout** [comment]
Fixed in v0.4.9
