### ISSUE TITLE
[FEATURE] Chose color icon companion app

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#142]
**Is your feature request related to a problem? Please describe.**
Now we can color background with the companion app, what is great, i love it.
But the icon color doesn't always match the background color, for example

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/19330e2c-d3fc-4b76-bdae-7672908a98b1)

Tile background is orange but icon is green

**Describe the solution you'd like**
Would be great that we also can change the icon color, than we can match the color, and in some cases we con only color the icon en leave backgrond normal

**Comment by pilpfiction** [comment]
Besides of the icon it would also be great to be able to set the text color

**Comment by StaffordBully** [comment]
Moved to Hdasboards
https://hdashboards.app/account/features/35
