### ISSUE TITLE
[BUG] multicard layout issue

### ISSUE THREAD

**Issue by pilpfiction** [mennovanhout/flutter-hdashboards-issues#145]
**Describe the bug**
Icon of first entry in multicards gets truncated, when header is displayed. Does not happen when no header is displayed or a title is added to the multicard (see screenshots).

**To Reproduce**
1. Go to HDashboard
2. Create a multicard with header
3. The truncated icon can already been seen without setting colors thru flows
4. Remove header - check result
5. Add title to multicard and move it to the top of the multicard - check result

**Expected behavior**
Icon should not be truncated for first item after multicard header is set!

**Screenshots**
Truncated icon with title header:
![Screenshot_20231222-161035](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/13a17565-2c21-4459-9e22-ae0971a12619)

No truncated icon with no header:
![Screenshot_20231222-162335](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/498a5cba-dcde-430e-b059-0b31b0f30197)

No truncated icon with title added to multicard:
(Title added to the top!)
![Screenshot_20231222-161614](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/42957854/95596911-e7d7-4c56-944e-7fb278f7008c)

**Using information (please complete the following information):**
 - OS: [e.g. Android]
 - Browser [e.g. chrome]
 - Version [e.g. Android app v0.5.0]

**Homey device**
 - Device: [e.g. Homey pro 2023]

**Additional context**
NA

**Comment by mennovanhout** [comment]
Android app. ios app or online? my android app doesn't seem to have this issue

**Comment by pilpfiction** [comment]
Android app ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

Pixel 8 pro / android 14

**Comment by pilpfiction** [comment]
I checked and the issue does not occur on my pixel tablet!

**Comment by mennovanhout** [comment]
i also have a pixel 8 pro let me check

**Comment by mennovanhout** [comment]
Fixed in next update
