### ISSUE TITLE
[FEATURE] confirmation for deleting tiles (multicard)

### ISSUE THREAD

**Issue by pilpfiction** [mennovanhout/flutter-hdashboards-issues#147]
**Is your feature request related to a problem? Please describe.**
By accident I deleted a multicard. As no confirmation is displayed, an unintentional deletion can happen easily. Recreation of a complex multicard becomes necessary.

**Describe the solution you'd like**
Confirm the deletion of a tile, especially for a multicard.

**Describe alternatives you've considered**
None available

**Additional context**

**Comment by StaffordBully** [comment]
A good idea is maybe to create a "trashcan" where deleted items will be stored for 7days and can be restored when needed.

**Comment by mennovanhout** [comment]
There is always a confirmation popup?
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/7ef62d1a-38ed-41d0-8b32-ff658f7f6fad)
