### ISSUE TITLE
[BUG] labels DC only change not live

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#148]
**Describe the bug**
When i change my label in device capabilities to a constant changing value it doesn't change, i need to refresh the dashboard
For example to see the lux value for my curtains

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/ed0867b9-46e2-4d9c-b549-733c5affbdb0)
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/8c1b4a2f-16a2-498a-b38d-f5b59e361d10)
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/81e726ae-a033-4792-8859-5fa438fb76d1)

if i change the text field to a constant changing value the label does change, think that label is connected to text field.

Would be great that label changes when needed or set in flow.

**Comment by mennovanhout** [comment]
Fixed in upcoming update
