### ISSUE TITLE
[BUG] Text Pushbutton doesn't change without refresh

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#149]
**Describe the bug**
I have created 3 pushbuttons
-   +1 min timerbutton
-   - 1 min timerbutton
-   On/Of device by set timer
But when i click +1 or -1 the text doesn't change, only when i refresh the dashboard, sadly

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/4d07cb2e-054b-4c5a-ae0a-6e61039a98fe)

**To Reproduce**
+1 and -1 Buttons in dc
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/1a10cae5-bdb3-4e08-9ec1-9f79768865e5)

Timerbutton in dc
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/5b91e8f9-9364-425c-9821-b15b9498b321)

i have made a variable where i store the value (min) of the timer
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/1e0181b6-0f01-4840-b5c8-cd46b5a3369b)

Flow setup timer
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/53469b8c-bc95-4877-8ed7-26e4f718824c)

Flow timer (on/off device)
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/3707ba0e-25c2-473e-950b-966531725259)

**Expected behavior**
When i hit +1 or -1 that the text immediately change, in homey it works fine

**Using information (please complete the following information):**
 - OS: [Android, Windows]
 - Browser [Chrome]
 - Version [Android app v0.5.0+27, web version v0.5.0+27]

**Homey device**
 - Device: [Homey pro 2023]

**Comment by mennovanhout** [comment]
Can you explain me what is supposed to change? for me it feels the same as #148

**Comment by mennovanhout** [comment]
Fixed in upcoming update
