### ISSUE TITLE
[FEATURE] Able to move multiple tiles at once in edit mode on website

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#15]
Be able to select multiple tiles by drawing a square / box and or us shift or ctrl mouse click and/or a selection box and then drag all tiles to another position on the dashboard.

When having lots of devices on a dashboard, repositioning is now tile for tile.

**Comment by mennovanhout** [comment]
Working with multiple tiles at the same time is not planned for now or the current future.

Thanks for the input however!
