### ISSUE TITLE
[BUG] Color reset when title of single tile is changed

### ISSUE THREAD

**Issue by pilpfiction** [mennovanhout/flutter-hdashboards-issues#150]
**Describe the bug**
A previous set background color of a tile is reset to default when saving the tile (even without changing anything).

**To Reproduce**
1. Change the background color of a single tile thru HD companion
2. Edit the tile and directly save it, without changing anything
3. Leave the edit mode 
4. See the tile on the dashboard (background color reset)

**Expected behavior**
Background color is not changed when tile is saved

**Screenshots**

**Using information (please complete the following information):**
 - OS: [e.g. Android]
 - Browser [e.g. chrome]
 - Version [e.g. Android app v0.5.0]

**Homey device**
 - Device: [e.g. Homey pro 2023]

**Additional context**

**Comment by StaffordBully** [comment]
is this a device capabilities tile?

**Comment by pilpfiction** [comment]
Yes

StaffordBully ***@***.***> schrieb am Sa., 23. Dez. 2023,
00:13:

**Comment by StaffordBully** [comment]
Make sure you delete the saturation, dim and hue from that device.
Than I wouldn't happen.

**Comment by pilpfiction** [comment]
Those are not defined!
Can't say for sure if I had those values defined at one point for the specific VD, but now they are not.

**Comment by StaffordBully** [comment]
okay, than i don't know, had the same issue as described above, but i had still those settings, after deleting them from the device i have no problem, sadly i can't help you. Menno wil look into it next year ;)

**Comment by mennovanhout** [comment]
Fixed in upcoming update.
