### ISSUE TITLE
[FEATURE] Add connection to Chronograph app

### ISSUE THREAD

**Issue by BOverdevest** [mennovanhout/flutter-hdashboards-issues#151]
I think Chronograph is the most popular app on Homey to manage timer and stopwatches.
It would be great if timer values could be shown on tiles on the dashboard.

Stability might be a thing with generating a lot of traffic (so maybe restrict it to minutes or x seconds)

Current workaround would be to connect a Number or Text  field in Device Capability to pick up the timer and from there pick it up in HDashboards

**Comment by mennovanhout** [comment]
Hi this is up to the chrono app to create a capability that updates a value. If they would add it in the app it works. Sadly I'm not going to write custom integrations for apps.
