### ISSUE TITLE
[BUG] Issue with multiple sliders from Device Capabilities

### ISSUE THREAD

**Issue by BOverdevest** [mennovanhout/flutter-hdashboards-issues#152]
**Describe the bug**
I have 1 DC device with 2 number fields, both set up as slider. (min=0, max=24, step=1)
In HDashboard i created two tiles to connect both separately., with control=true.
each tile shows the value of the number field as expected
both sliders are however both connected to field 1.
Changing slider on tile 2, will change the value on field 1/tile 1/slider on tile 1

Via Long press, the 2nd slider can be set as expected

**To Reproduce**
1. Create DC device with 2 numbers fields, both as sliders
2. in HDashboards create two tiles, connected to each field
    Show Control = true. (Show capability label does not matter)
3. move either slider and value for field 1 will change

**Expected behavior**
Slider on tile connected to field 2 should change the value for field 2, not 1

**Screenshots**
in the screen shot both sliders have a value of 0-24.
So the slider in tile two should be positioned on the far right

I created a third tile to show the button of the DC device, by leaving the capabilty label empty during set up in HDashboard.
This includes the button and slider for number field 1.
I hope we can have the option to create a tile with only a button, via being able to selecte te button capability during set up.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/37892181/9e8d4f80-2bb4-4622-b349-8b1e1792bc9b)

**Using information (please complete the following information):**
 - issues is on web and IOS

**Homey device**
 - Homey 2023

**Additional context**

**Comment by mennovanhout** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/78de892a-d37d-41cf-b11b-dda431d8b571)
Fixed in upcoming update
