### ISSUE TITLE
[BUG] Slider breaks ON/OFF on Capability Device

### ISSUE THREAD

**Issue by BOverdevest** [mennovanhout/flutter-hdashboards-issues#153]
**Describe the bug**
When a control is added via a field ( Slider, Set Volume, might be more) this breaks the working of the ON/OFF of the device.
Clicking ON will turn on the tile (make it green) but when turning it off, it stays green.

**To Reproduce**
1. Create Capability Device
2. add an On/Off button
3. On the dashboard add the device, keeping the capability tag empty
4. clicking on/off in Homey will be reflected on the tile
5. add a number field with a slider
6. on the dashboard the tile will have a slider and a button
7. try to do the same as step 4 --> tile stays green

**Expected behavior**
On/OFf should work in step 7 same as in step 4

**Screenshots**

**Using information (please complete the following information):**
 - OS: web, + iphone
 -  - Browser;chrome
 - Version [e.g. Android app v0.0.7, web version v0.0.7]

**Homey device**
 - Homey pro 2023
 -
**Additional context**
- using 'Set volume' for the field also results in same defect , but shows a on/off button
- Using Target Temperature, there is no defect, also shows an on/off button

**Comment by mennovanhout** [comment]
Good question this actually is expected behaviour for curtains etc

**Comment by mennovanhout** [comment]
What you should do is add in custom capabilities that the slider returns to 0 when the device is being turned off.

**Comment by mennovanhout** [comment]
Wait i might create a fix to do it automatically i already do it for lights.
