### ISSUE TITLE
[BUG] Title on Tado thermostat does not change when capability is empty

### ISSUE THREAD

**Issue by BOverdevest** [mennovanhout/flutter-hdashboards-issues#156]
**Describe the bug**
For titles linked to Tado devices (Smart Thermostat, Smart Radiator) the title does not change to the value set in the edit screen when the capability line is kept empty.
When a capability line is set, the title is updated.
I assume it is linked to the thermostat tile

**To Reproduce**
1.  Create a new tile and link to a thermostat device
( based on assumption it is true for all thermostats)
2. enter a title
3. keep the capabilty asis
4. press save
5. title should be name of device
6. edit the tile
7. pick a capability
8. save
9. title is per settings

**Expected behavior**
Title should be as set in the settings 

**Screenshots**
<img width="443" alt="image" src="https://github.com/mennovanhout/flutter-hdashboards-issues/assets/37892181/98a390b8-4659-4ec0-8729-11aaeb5aa9df">
<img width="599" alt="image" src="https://github.com/mennovanhout/flutter-hdashboards-issues/assets/37892181/05a373ed-0134-4f4c-9e62-9b74167af536">

**Using information (please complete the following information):**
 - OS: iOS, Web, Chrome

**Homey device**
 - Device: Homey pro 2023

**Additional context**

**Comment by mennovanhout** [comment]
Yep you are right! Seems that I've forgotten to update the code of the thermostat tile! Thanks for letting me know

**Comment by mennovanhout** [comment]
Fixed in next update
