### ISSUE TITLE
Device (Fibaro door sensor) its highlighted in any state [BUG] 

### ISSUE THREAD

**Issue by Supra66** [mennovanhout/flutter-hdashboards-issues#158]
Door sensor from Fibaro - Contact alarm shows the state false or true, but it doesn't change the highlighting - its same on true and on False. Other sensors (not from Fibaro) doesn't do this.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/94135198/f3ff4fa2-2d6d-40cf-9e2c-5bbc5b4ab334)
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/94135198/0b84b10a-e369-4ab4-a5d8-7beacd9fd071)

**Using information (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Version [e.g. Android app v0.5.0+27

**Homey device**
 - Device:Homey pro 2023

**Comment by StaffordBully** [comment]
That's strange, I have no problem
![SmartSelect_20231230_135338.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/b0a7650b-2f95-4ac9-92b7-6ad80ac15cac)

**Comment by StaffordBully** [comment]
Is the battery empty? 
What is the status on long press?

![SmartSelect_20231230_135528.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/9ac3751e-8f0a-427c-a068-954f3a01470a)

**Comment by StaffordBully** [comment]
Now I see that Sabotage alarm and contact alarm are double. Wil make a github about that

**Comment by Supra66** [comment]
OH ok I found the problem. It was the sabotage alarm. But this is also strange for me now.
Because I use multiple layout and I have a multiple layout for temperature multiple layout for doors and so on. And if someone opens the door it will highlight not only in the door layout but also in the temperature layout  (because I take the temperature from the door sensor)
Same for other devices like Aqara TVOC - I will display the Temperature but if there is a VOC alarm it highlight the temperature. I guess the Highlighting should be only for the one function  not for all on the device.

**Comment by StaffordBully** [comment]
indeed, it must only highlight by selected label, maybe create a github about that, than can menno check it.
