### ISSUE TITLE
[FEATURE] Able to set an alias name for a tile, which replaces homey name on dashboard

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#16]
To add an alias name in a tile, instead of the real Homey device name.

**Comment by mennovanhout** [comment]
Decided to close this for now. Sorry:

For now it doesn't seem like a good idea because you will have no way to remember which device it is after a while.

**Comment by MP-ICT-Diensten** [comment]
If we can edit the tile, you will see the real name there, it is not gone, but dashboard looks much better. The competition dos have it (sharptools) and I think that it is very handy. They call it label, for hdashboard alias is a possible name.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/a0580b30-ccd1-453d-96f6-fedbdb7eefc1)

**Comment by mennovanhout** [comment]
Okay I am reopening the issue

**Comment by jeesnl** [comment]
I think this is a Must have to maka the dashboard nicer .

**Comment by ronaldsomers** [comment]
Zou een zeer goede toevoeging zijn!

**Comment by MP-ICT-Diensten** [comment]
Also a basic functionality just like the tile edit possibility, for me more important than multi tile (which is absolutly very nice to have), but this one and edit tile are really missed.

**Comment by mennovanhout** [comment]
@MP-ICT-Diensten Edit is done! This requested feature is available in multicard and will soon come to all cards!

**Comment by mennovanhout** [comment]
Done and will be added in next release v0.4.4
