### ISSUE TITLE
[FEATURE] Devicestatus aanpassen in On en Off

### ISSUE THREAD

**Issue by eilko** [mennovanhout/flutter-hdashboards-issues#161]
**Is your feature request related to a problem? Please describe.**
De device status wordt weergegeven als False of True, terwijl het voor de eindgebruiker eerder Aan of Uit is 

**Describe the solution you'd like**
Een optie om True/False aan te passen naar Aan/Uit, Uit/Aan, Ja/Nee, Nee/Ja

**Comment by mennovanhout** [comment]
Thanks

**Comment by eilko** [comment]
found another case today for the Aqara door sensors: Locked / Unlocked, Closed/ Open

**Comment by mennovanhout** [comment]
I found out that apps give a true and false title this will be used in the upcoming update and should fix it!
