### ISSUE TITLE
[FEATURE] Color settings in a variable

### ISSUE THREAD

**Issue by Don-Vittorio** [mennovanhout/flutter-hdashboards-issues#163]
**Is your feature request related to a problem? Please describe.**
It's a feature request. I like to have my colors consistent all over my dashboards.

**Describe the solution you'd like**
I like to have the possibility not to enter ff0000 for red, but also the possibility to use a variable (like: Color red, which contains ff0000), so I can change my favorite colors by just changing the variable.

**Describe alternatives you've considered**
Non

**Additional context**
I might consider to use other colors, like more light blue (because the current blue is a kind of harsh).

**Comment by mennovanhout** [comment]
I'll check this soon!

**Comment by mennovanhout** [comment]
I've checked it, sadly this is a limitation by Homey and not me.
I could create flow cards that accept colors as text and not with a color picker (workaround for homey).

But that results in double cards etc. I would recommend to give this feedback to Homey to create color variables.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/ff5fcff0-57c3-4190-a17a-a4e2a78fd702)
