### ISSUE TITLE
[BUG] Two temporary notifications do result in a persistent notification

### ISSUE THREAD

**Issue by Don-Vittorio** [mennovanhout/flutter-hdashboards-issues#164]
**Describe the bug**
When I send two temporary notifications, the second one becomes persistent.

**To Reproduce**
1) send a temporary notification
2) send a second temporary notification
3) the first one dissapears after x seconds.
4) the second one stays on the dashboard.

**Expected behavior**
I expect the second one to disappear after x seconds too.

**Screenshots**
Not available

**Using information (please complete the following information):**
Nest

**Homey device**
Homey pro 2023

**Additional context**
None

**Comment by mennovanhout** [comment]
Thanks!

**Comment by mennovanhout** [comment]
Fixed in upcoming update.
