### ISSUE TITLE
[FEATURE] Give dashboards in dashboards an alternative title

### ISSUE THREAD

**Issue by Don-Vittorio** [mennovanhout/flutter-hdashboards-issues#166]
**Is your feature request related to a problem? Please describe.**
I have dashboards on iPad, iPhone and 3 Google Nests. All start with the most important information, but I can zoom in to individual zones. These zones are in dashboards. So I have a dashboard "Living room" at least 3 times, but with different lay-out and content. So I would like to name my dashboards "iPad Living room", "iPhone Living room" etc. But I like to give it a display name "Living room". So an alternative title like on devices on the dashboard.

**Describe the solution you'd like**
Give the possibility to give an alternative title to a dashboard in a dashboard.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mennovanhout** [comment]
Fixed in uncoming update.
