### ISSUE TITLE
[FEATURE] Possibility to change the color of a dashboard in a dashboard.

### ISSUE THREAD

**Issue by Don-Vittorio** [mennovanhout/flutter-hdashboards-issues#167]
**Is your feature request related to a problem? Please describe.**
I have dashboards on iPad, iPhone and 3 Google Nests. All start with the most important information, but I can zoom in to individual zones. These individual zones can become active, or something can happen there. So I would like to be able to change the color of a dashboard in a dashboard.

**Describe the solution you'd like**
The nicest option is to be able to set the color to a dashboard directly in the companion app, so a new type of flow card.

**Describe alternatives you've considered**
Another option to keep it in this case on identifier.

**Additional context**
None.

**Comment by eilko** [comment]
I tried something similar. When zone becomes active change the color of the matching dashboard tile. Doesn't seem to work

<img width="920" alt="Screenshot 2024-01-07 at 13 34 33" src="https://github.com/mennovanhout/flutter-hdashboards-issues/assets/1078401/6475de10-e892-4208-b6c5-34f5c7b5d811">

**Comment by mennovanhout** [comment]
@eilko @Don-Vittorio support for the color mode on dashboard tiles will soon be added.

**Comment by mennovanhout** [comment]
Added in next update
