### ISSUE TITLE
[FEATURE] Possibility to word wrap (as an option)

### ISSUE THREAD

**Issue by Don-Vittorio** [mennovanhout/flutter-hdashboards-issues#168]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to display information that is too long for a virtual device in a dashboard. In that case I would like an option to use word wrap. Would be great if I can use soft-enters (shift-enter) to achieve forced word-wrap (I already used this before we got HDashboards in favorite devices.

**Describe the solution you'd like**
A toggle "Word wrap" in the edit mode of an object.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eilko** [comment]
see also #155

**Comment by mennovanhout** [comment]
Duplicate of #155
