### ISSUE TITLE
[FEATURE] Recognize buttons from information objects

### ISSUE THREAD

**Issue by Don-Vittorio** [mennovanhout/flutter-hdashboards-issues#169]
**Is your feature request related to a problem? Please describe.**
I have virtual devices with a button behind it and virtual devices just giving information. I would like to see the difference somehow.
I think you know when there's a button behind it, because of the message at the bottom.

**Describe the solution you'd like**
My idea is to have a somewhat bolder line around the device. But I'm not an UX designer.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mennovanhout** [comment]
I don't really understand it, sorry ;(

**Comment by Don-Vittorio** [comment]
When my Device capabilities virtual device contains a button, I like to recognize this in the ui as a kind f button.

**Comment by Don-Vittorio** [comment]
Display. It works great, but I like to see it works like a button. So before I click on it.

**Comment by mennovanhout** [comment]
Do you have a screenshot :D?

**Comment by Don-Vittorio** [comment]
![IMG_1173](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/123970971/a37a5403-a8b0-4cf9-901f-db0da059b673)
As you can see, my airco's, heaters and ventilation are buttons. Temperature and air quality are just information objects.
It would be great if I can recognize **before** I push an object, I know something will happen (especially my wife).

**Comment by mennovanhout** [comment]
Ah i get it!

**Comment by mennovanhout** [comment]
No that is indeed regarding the request to make it clear what a info or touch button is.
I would recommend changing the color via the companion app.
