### ISSUE TITLE
[FEATURE] Able to move/copy tiles to another dashboard

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#17]
Be able to move or copy tiles to another dashboard, using multi selection

**Comment by mennovanhout** [comment]
Sorry this is not planned, perhaps i will add a duplicate dashboard feature in the future.

**Comment by DannyBorremans** [comment]
Is copying tiles from one Dashboard to another still not planned ?  This would be a helpfull feature when re-organising dashboards.

**Comment by mennovanhout** [comment]
> Is copying tiles from one Dashboard to another still not planned ? This would be a helpfull feature when re-organising dashboards.

We transfered to a new issue system. its on the planning
