### ISSUE TITLE
[FEATURE] hide title

### ISSUE THREAD

**Issue by nickpauwels1988** [mennovanhout/flutter-hdashboards-issues#171]
**Is your feature request related to a problem? Please describe.**
Title/title bar should be optional

**Describe the solution you'd like**
Checkbox to hide titles?

**Describe alternatives you've considered**

**Additional context**

**Comment by mennovanhout** [comment]
You mean the big appbar on top?

**Comment by nickpauwels1988** [comment]
Titles on images, flow cards and the like

**Comment by mennovanhout** [comment]
Done in upcoming update
