### ISSUE TITLE
[FEATURE] Ability to give a title to dashboard cards to be used instead of the name of the dashboard

### ISSUE THREAD

**Issue by nickpauwels1988** [mennovanhout/flutter-hdashboards-issues#172]
**Is your feature request related to a problem? Please describe.**
At this moment the dashboard card takes the title of the dashboard,

**Describe the solution you'd like**
Add a title option, if filled in, the dashboard card uses the title option instead of the title of the dashboard

**Comment by eilko** [comment]
the same as #166

**Comment by mennovanhout** [comment]
Thanks @eilko saves me time to check everything ;)
