### ISSUE TITLE
With klikaanklik uit Koolmonoxide and rookmelder you cannot select battery level 

### ISSUE THREAD

**Issue by Platvoetje** [mennovanhout/flutter-hdashboards-issues#175]
**Describe the bug**
With Klikaanklikuit devices "Koolmonixide"and "Rookmelder"you cannot choose the battery level

**Expected behavior**
to select the batterylevel as you can do that with other devices which has an battery as in homey it is available

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/140010634/44c72e63-7552-4671-bbfb-cc62eca3d0f9)

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/140010634/b384bf32-86e8-401e-ad7b-52b878b2b676)
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/140010634/a5b1a89e-69b7-463a-a460-54d17868d86a)

**Using information (please complete the following information):**
 Iois and Windows 10

 - Device: Homey 2023

**Comment by mennovanhout** [comment]
is there really a percentage or just a ok status etc when you longpress it?

**Comment by Platvoetje** [comment]
Hello
Yes I see it only OK status, but that can also be displayed or just the
battery picture?



Op do 11 jan 2024 om 14:51 schreef Menno van Hout ***@***.***>

**Comment by mennovanhout** [comment]
In that case it's not a bug but a way that Homey works.
Battery status with ok etc are not seen as capabilities by Homey.
In this case you can actually only use battery alarm that's also where Homey bases the ok or not ok on.

**Comment by Platvoetje** [comment]
Oké
That’s a pity then I need to buy other ones and replace them any suggestions

Op do 11 jan 2024 om 15:45 schreef Menno van Hout ***@***.***>

**Comment by mennovanhout** [comment]
What is wrong with using the battery alarm as display value?

This will tell you if the status is okay/not. Also your device will become orange when it needs battery replacement.

**Comment by Platvoetje** [comment]
That is true
Let me think about it
Sorry for the wrong bug report

Thanks
Friso

Op do 11 jan 2024 om 15:58 schreef Menno van Hout ***@***.***>
