### ISSUE TITLE
When using Euro to be shown in a tile the Euro sign is always behind the amount

### ISSUE THREAD

**Issue by Platvoetje** [mennovanhout/flutter-hdashboards-issues#176]
**Is your feature request related to a problem? Please describe.**
When use Euro amount to be shown in a tile the Euro sign is always behind the amount.
For Watt and KW it is good but not for the money sign

**Describe the solution you'd like**
The euro sign € before the amount so like this €43 and not 43€ 

**Describe alternatives you've considered**
no
**Additional context**

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/140010634/ecc7c92f-66c3-4613-945c-33cd69398a13)

**Comment by mennovanhout** [comment]
How does Homey display it?

**Comment by Platvoetje** [comment]
Hello
Yes your right it is wrong in homey in the power buyout app



Op wo 10 jan 2024 om 21:07 schreef Menno van Hout ***@***.***>

**Comment by mennovanhout** [comment]
Thanks for checking!
