### ISSUE TITLE
[BUG/FEATURE] Empty squares are saved

### ISSUE THREAD

**Issue by eilko** [mennovanhout/flutter-hdashboards-issues#180]
**Describe the bug**
When I make a dashboard of 12 horizontal squares in a webbrowser with more space on the right, also the empty/unused squares on the right are saved.  When I make the webbrowser screen a bit smaller, but still much larger than the 12 squares the whole dashboard gets messed up. 

**Expected behavior**
Only save the maxed used horizontal squares. 

**Screenshots**

dashboard made in web version with the intention to show in iPad mini app. 
<img width="1792" alt="Screenshot 2024-01-16 at 18 42 26" src="https://github.com/mennovanhout/flutter-hdashboards-issues/assets/1078401/fcf59080-f6cb-4fc4-a8df-5fd1ca61a6a7">

changing the web browser screen a little bit. 

<img width="1677" alt="Screenshot 2024-01-16 at 18 42 43" src="https://github.com/mennovanhout/flutter-hdashboards-issues/assets/1078401/97d0c2c7-601b-4c3e-9474-209eb4e8ea52">

**Using information (please complete the following information):**
 - OS: macos
 - Version: latest web version on Safari

**Homey device**
 - Device: Homey pro 2023

**Comment by eilko** [comment]
can be solved by used the max setting in the web client. Still not an obvious option for new users

**Comment by mennovanhout** [comment]
It indeed is expected behaviour but indeed will try to make it more obvious
