### ISSUE TITLE
[FEATURE] Change color background multicard

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#181]
**Is your feature request related to a problem? Please describe.**
No, just a little upgrade

**Describe the solution you'd like**
Change color of complete multicard itself.
For example i have 2 devices and set the background color the same as backgroundcolor dashbord.
But top and bottum are stil other color

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/ff730e07-058f-497a-a5fd-5f32caf4ad87)

**Describe alternatives you've considered**
Would also be great to chose a border color

**Comment by mennovanhout** [comment]
Done in v0.5.2
