### ISSUE TITLE
[FEATURE] Special tile to add html code in

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#19]
Having a code tile where you can add an iframe or gadget in, so that you can do something like a rain radar widget:  https://www.weeronline.nl/widgets#radar  or this one: https://www.buienradar.nl/overbuienradar/gratis-weerdata

Or even a traffic congestion widget

**Comment by baloe1541** [comment]
Yes that’s sounds cool

**Comment by mennovanhout** [comment]
I've checked a lot if this was possible, but sadly it isn't since we use Flutter as technlogy. And that actually doesn't support HTML because it doesn't use HTML from itself. ;(
