### ISSUE TITLE
Label with Device Type when adding Device.

### ISSUE THREAD

**Issue by markmastop** [mennovanhout/flutter-hdashboards-issues#2]
Label with Device Type when adding Device.

I've got multiple names that are the same when adding. If I can see the device type then it is easier to identify which device I need to add.

As example I've added a screenshot.

<img width="566" alt="image" src="https://github.com/mennovanhout/flutter-hdashboards-issues/assets/3921342/bbd395b1-f775-425d-88be-7d2b41598dec">

**Comment by mennovanhout** [comment]
I will look into it!
