### ISSUE TITLE
[FEATURE] Favourite icons

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#20]
Sometimes is hard looking for the best icon for the tile. Maybe when you select an icon show the name of the icon too, than it's next time easier. 

Maybe last used icons or possible to create a tab with favorite icons?

**Comment by MP-ICT-Diensten** [comment]
Edit the title to tell what you like to have ;)

**Comment by mennovanhout** [comment]
Sorry not planned will add #4 edit mode.
