### ISSUE TITLE
[FEATURE] Show multiple values of a device in the tile (and select them)

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#21]
Lots of homey devices have multiple values.  Now we can only use one value and to show other values we can add the same device multiple times, but with a different value for label.  

To be able to show multiple (selectable via a checkbox) values in the tile, instead of the default icon from homey.

For example like this:
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/9e86dd94-85c7-4b21-ad65-a87c0139963c)

**Comment by mennovanhout** [comment]
Working on this!
