### ISSUE TITLE
[FEATURE] A Clock & Date tile

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#23]
A tile which displays time and date in a format we choose:

12/24 hour  12:00am  24:00
Date time   short or long, based on language of browser  
Short NL:   31-12-2023   1-5-2023
Long NL:    31 december 2023
Short EN:   12-31-2023   5-1-2023
Long EN:    December 31, 2023

**Comment by mennovanhout** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/84512fa3-51f7-499b-b352-7a51c261317a)
done in next update
