### ISSUE TITLE
[FEATURE] Every dashboard and tile has its own ID (UUID or SID)

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#24]
If  creating a dashboard or a tile, save it in the database with an unique ID and if the tile is copied give the copy a new unique ID, keep the ID when moved.

If deleting a dashboard or tile only delete the dashboard/tile with that ID and not the once with the same name.  

Dupicate name is then also possible and will not give issues if names are the same in a dashboard or on multiple dashboards

**Comment by mennovanhout** [comment]
duplicate of #8
