### ISSUE TITLE
[BUG] Icons are not shown in already created devices

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#25]
If creating a device, then the icon from homey is shown as below in the left tile. But if the tile is older, then the icon is not registered, like in the rights one.  I now must delete the device and readd the device.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/4c1a5635-8cc6-43d8-94ec-85837886ce6b)

A solution is auto scheduled rescan on background one a day? Or have a maintenance button to collect the last icon url's from homey for all tiles on a dashboard or for all tiles on all dashboards. 

I presume that the icon's are loaded from homey and not copied into hdashboard db. If icons are refreshed on homey, for example by an updated app with new icons, then the reference would probably the same.  

Tiles like AVD's from Device Capabilities can be updated afterwards in the Homey.

**Comment by mennovanhout** [comment]
Solved in next update, i'm saving the raw svg when adding a tile now.
