### ISSUE TITLE
[FEATURE] Link tiles to make groups.

### ISSUE THREAD

**Issue by RayverPro** [mennovanhout/flutter-hdashboards-issues#27]
For example: I have a floor light with 3 hue lamps. Now I need to make 3 separate tiles. It should be nice to have the possibility to link these 3 tiles so that you can change (on/off, color) it at once by pressing on that connected group tile.

**Comment by MP-ICT-Diensten** [comment]
You can use the <group> app or the Device Capabilities app (make a virtual device). But the <group> app is probably the most easy.  Install it on your home, create the group device and you can switch them on/off via this group devices.

Then in hdashboard you can add the group device and control them by one click.  With grouped devices also dim and color are possible.

My advices is not to implement grouping of devices in the dashboard, but leave that function to the homey.
