### ISSUE TITLE
[BUG] Application crashes when switching "On/Off" LG web-os 

### ISSUE THREAD

**Issue by RayverPro** [mennovanhout/flutter-hdashboards-issues#29]
**Describe the bug**
Application crashes when making a switching "On/Off" LG web-os tile.

**To Reproduce**
I made a tile to switch "On/Off" and control volume on a LG Web-Os television. After that the app is crashing continuously on my mobile Iphone by saying "connecting to Homey socket" 
When I go back one page and restart the app again It starts, but after a several time it crashes again. Also by not using/pressing on that tile.
The web app on my Imac don't have that issue.
After deleting the "LG" tile (on Imac) everything is working normal on my Iphone mobile and craches not anymore.

**Comment by RayverPro** [comment]
The same issue seems to happen as you make a "ziggo homebox" tile

**Comment by mennovanhout** [comment]
Luckily I have a LG OLED WebOS tv as well. I am going to try reproducing it, so I can solve it.

**Comment by mennovanhout** [comment]
I actually cannot reproduce this. Can you reach out to me on Discord?

**Comment by mennovanhout** [comment]
Do you still have this problem since the latest update v0.0.8?

**Comment by RayverPro** [comment]
I'm for work in Germany at the moment. Friday I will test it with the new release!

**Comment by mennovanhout** [comment]
Let me know if you still have issues

**Comment by RayverPro** [comment]
Just a minute ago I checked it, and so far it works correctly without any crash!
