### ISSUE TITLE
[BUG] Opening the web-app on a old (9years) Ipad

### ISSUE THREAD

**Issue by RayverPro** [mennovanhout/flutter-hdashboards-issues#30]
I don't know why, but it seems to be impossible to open the web-app on a quite old Ipad (2014).
The idea was to use this one on the wall for the dashboard.
He says, "Safari can't open the website because it can't find the server" 
Any other website what I use for homey still opens on the device. Homey.app for example!
Any suggestions?

**Comment by mennovanhout** [comment]
using the right url? https://web.hdashboards.app

**Comment by RayverPro** [comment]
The IPad runs on 9.3.6

When I open the website it opens, but after pressing on the web app button I get a totally white page.
