### ISSUE TITLE
[FEATURE] Light function for virtual lights

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#31]
I Have in homey virtual lights.
When added the tile to Hdashboards it recognize it as light but when I change color to the virtual light noting happens. Hope that the resent function for lights, recognize and change color also wilt be able for this.

Thx ;)

**Comment by mennovanhout** [comment]
Heyyy @StaffordBully Does your virtual light has the folowwing capabilities:
- light_hue
- light_saturation
- dim

With those 3 capabilities it's seen as a colored light.

**Comment by StaffordBully** [comment]
I have the ligt setup as
Hue light
Saturation
Light temp

If I add dim the tile keeps loading

**Comment by mennovanhout** [comment]
Perfect this issue is resolved :D
