### ISSUE TITLE
[FEATURE]  Integration with Heimdall alarm Keypad or something 

### ISSUE THREAD

**Issue by baloe1541** [mennovanhout/flutter-hdashboards-issues#33]
A nice alarm pad with PIN code what works together with Heimdall

**Comment by mennovanhout** [comment]
There is a new selector on longpress in: https://testing-web.hdashboards.app/
Does this satisfy your needs?

**Comment by baloe1541** [comment]
Can’t deactivate the alarm button not visible 
![Uploading IMG_4374.jpeg…]()

**Comment by mennovanhout** [comment]
Can you reach out to me on Discord?
