### ISSUE TITLE
[BUG] delete dashboard and select after the delete another dashboard gives the deleted dashboard

### ISSUE THREAD

**Issue by DanGer61** [mennovanhout/flutter-hdashboards-issues#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Using information (please complete the following information):**
 - OS: [e.g. iOS, Android, Windows]
 - Version [e.g. Android app v0.0.7, web version v0.0.7]

**Homey device**
 - Device: [e.g. Homey pro 2023, Homey cloud]

**Additional context**

**Comment by mennovanhout** [comment]
Solved in v0.1.0
