### ISSUE TITLE
[BUG] Insight grafieken niet te vinden in my homey app

### ISSUE THREAD

**Issue by DanGer61** [mennovanhout/flutter-hdashboards-issues#35]
Bij het maken van een flow om elke 30 minuten een grafiek te maken, vind ik bij de THEN optie Insight Grafieken niet terug. Ib de Homey toepassing wel , maar ik krijg geen THEN kaart

**Using information (please complete the following information):**
 - OS: [e.g. iOS, Android, Windows]
 - Version [e.g. Android app v0.0.7, web version v0.0.7]

**Homey device**
 - Device: [e.g. Homey pro 2023, Homey cloud]

**Additional context**

**Comment by StaffordBully** [comment]
Did you use advanced flow?

**Comment by DanGer61** [comment]
No

**Comment by DanGer61** [comment]
In advanced flow i got it

**Comment by StaffordBully** [comment]
It only works in advanced flow.
But at the moment you can't load insights to Hdashboards because Menno created a new app that first need to approved by home, next week will it be possible again. More about that on Discord.

**Comment by DanGer61** [comment]
Ok thanks

**Comment by mennovanhout** [comment]
This is indeed what @StaffordBully says and it's not an issue of hdasboards. I might have made both apps but this is not really the correct place to put issues about insights graphs.
