### ISSUE TITLE
[FEATURE] Ability to edit tiles

### ISSUE THREAD

**Issue by markmastop** [mennovanhout/flutter-hdashboards-issues#4]
After a tile is added you can not change the tile. To change to option for example.

**Comment by MP-ICT-Diensten** [comment]
This one is one I really really miss, to be able to edit tiles after creating. It should be on the topmof your list, because it is basic functinality and one which really holds me back to start using HDashboard.

**Comment by mennovanhout** [comment]
Pinning this issue since I agree it becomes important @MP-ICT-Diensten

**Comment by mennovanhout** [comment]
Done in v0.4.2
