### ISSUE TITLE
[BUG] No capabilities found

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#42]
**Describe the bug**

<@202351617461321728> Did you look at my reported issues a couple of days ago? They are not solved yet.                        Fond a few errors in the test version:
1. When long-press on a sensor i get the message “No  capability’s fond” although there are 2 tabs with capability’s. Maybe there are more device types where this doesn’t work. 
2. When long-press on a normal device, and come back to the dashboard the tile doesn’t response any more. Need to go back to the dashboard overview and back to the dashboard then the tile is working again.

**Expected behavior**

**Screenshots**

**Using information (please complete the following information):**
 - OS: Web version 0.2.0

**Homey device**
 - Device: Homey Pro 2033

**Additional context**

**Comment by mennovanhout** [comment]
@jeesnl Bug 1 is resolved I can also reproduce bug 2 will fix it soon!

**Comment by jeesnl** [comment]
Perfect, it’s working now.
