### ISSUE TITLE
[BUG] Image doesn't refreshing.

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#43]
I have created a image that shows the actual power usage from my home.
But the image doesn't change, even when I set up forcing. I need to refresh the dashboard to let the image change.
See usage cirkel in screenshot

 ![Screenshot_20230929_214055.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/60ba624f-9159-442c-992e-30184352f092)

**Comment by mennovanhout** [comment]
I actually cannot reproduce this, tested it with a link that gives me a random images that works perfect, please talk to me on discord so i can see if we can re-open this issue.
