### ISSUE TITLE
[FEATURE] Normal device becomes fully green when its on.

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#44]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like that when normal device is on the tile becomes fully green like a dimmable tile which is fully on (100%).

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mennovanhout** [comment]
Done in next update
