### ISSUE TITLE
[FEATURE] Change the Icon of a tile

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There should be an option to change the Icon for all the tiles. You can personalize the Dashboard much more to make it more clear which function the tile is.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by mennovanhout** [comment]
This is already done, when adding a device you can change the icon by clicking on it. This will also be added on the edit screen of cards that is coming soon.

**Comment by jeesnl** [comment]
This works only for tiles of type device, not for tiles of type flow.

**Comment by mennovanhout** [comment]
Added!  in 0.2.7
