### ISSUE TITLE
[FEATURE] Option to set the main dashboard per device

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#47]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
There should be a way to choose which dashboard is the main dashboard for each device (Phone, Tablet or PC) the user is using.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by jeesnl** [comment]
If i share the url of the correct dashboard via authenticated url.
If i open that url the correct dashboard is opened, but if i put it on my startscreen with a shortcut it does not work. I have to logon again and i get the standard login screen.

**Comment by mennovanhout** [comment]
done in v0.3.1
