### ISSUE TITLE
[BUG] Cannot turn device of type "Sunshade" On/Off

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#48]
**Describe the bug**
In Homey you can an device of type "Sunshade" On and Off. Then the Device becomes fully opens or close via the tile.
In hdashboads noting happens when you tick the tile.

**To Reproduce**
click on a tile of type "Sunshade"

**Expected behavior**
When you click on a tile of type "Sunshade" the device should go fully open or closed.

**Comment by mennovanhout** [comment]
Ah so that is supported within Homey?

**Comment by mennovanhout** [comment]
And do you get a slider? Or also not

**Comment by jeesnl** [comment]
Yes Homey supports this.  I have a slider but it's strange to me that this 'On/Off' is not supported by Hdashboards.

**Comment by mennovanhout** [comment]
I just checked again, are you willing to send me a video either here or on discord about how this works in the homey app?

**Comment by jeesnl** [comment]
Herewith 2 movies 1 from the Screen tile on/off and one from the Bose Sounbar which have the same issue. If you want a separate Issue for the 2nd please let me know. 


https://github.com/mennovanhout/flutter-hdashboards-issues/assets/39216786/538deab6-33c6-4099-ba0c-434d440768a5


https://github.com/mennovanhout/flutter-hdashboards-issues/assets/39216786/42db6833-5587-4954-a702-f459b523f9a5

**Comment by mennovanhout** [comment]
Works in next update.
