### ISSUE TITLE
[BUG] Image list:  Show only devices with >0 images

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#49]
When creating an Image tile in 0.2.0 and I search, only show the devices which have images. Thus filter and only show devices if device has more than 0 images .

I now get a list of 100 devices without images and 3 with image....

**Comment by mennovanhout** [comment]
This has been a bit of a dilemma. Ive tried that but people complained that my device list was not accurate and they couldn't find their device. As a result I showed all of them with a counting in the selector

**Comment by MP-ICT-Diensten** [comment]
When you have a few devices and very good and young eyes, it is not a problem, but my vision is a bet less and eyes are older and a list with I support more than 100 devices.  I keep scrolling ....    so a filter which filter out all devices without images will minimize that list very much.

**Comment by mennovanhout** [comment]
good idea I'll take a look at it immedietly!
