### ISSUE TITLE
[FEATURE]  Better readability

### ISSUE THREAD

**Issue by roko14** [mennovanhout/flutter-hdashboards-issues#5]
I think its mentioned before; bigger icons and bigger text. For now, my tiles are bigger than i would like. But even now the text is too small to read comfortible. And the icons are also too small to recognize fast..
Two foto's to show the issue better
![Hdashboards](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/130743612/60d7cf74-3c50-46f7-be4c-d245b79f1718)
![Homey Dash](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/130743612/6a8db2fe-b82e-40e6-bdb5-5792343578f6)

**Comment by StaffordBully** [comment]
Agree, the text is to small.

**Comment by mennovanhout** [comment]
Thanks @roko14 first of all super nice tablet!!!! love the way you use it.
I am gonna work on it!
