### ISSUE TITLE
[BUG] in Web app, changing label gives search window, no label possible now

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#50]
IN web app, add an device and clikc on label, then I get a search windows, like searching for devices, but there is nothing to search for, it should be text input to have a new label name,

So currently the label search leads to nothing and it is impossible to type a label name.

**Comment by mennovanhout** [comment]
Label is scanning for capabilities. Like temperature or luminous on motion sensors

**Comment by MP-ICT-Diensten** [comment]
Change label to Capabilities label    the word label suggests a wider use and or possibilities.
