### ISSUE TITLE
[BUG] Airco can't switched on/off

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#51]
**Describe the bug**
If I click on the tile nothing happens. Icon is also Grey.

**Expected behavior**
When I click on the device that is goes on and icon turns green, click again goes off and icon turns red

**Screenshots**
![SmartSelect_20231001_095345.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/4b904056-1b62-4366-88fd-358df93bf7ad)

**Using information (please complete the following information):**
 - Browser Chrome. 
Dashboard v0.2.0

**Homey device**
 - Device: Homey pro 2023

**Additional context**
Isn't it possible to add slider?
The plus and minus are nice to view but not to handle. When I need to change example 3 degrees I need to click very slowly because it's need to send every 0,5 degree to the device

**Comment by mennovanhout** [comment]
I don't think this device implements the onoff capability, does homey support you just clicking it?

**Comment by StaffordBully** [comment]
Is put the device always on/off by flow on homey

**Comment by mennovanhout** [comment]
I'll check <3

**Comment by mennovanhout** [comment]
Fixed in v0.2.5
