### ISSUE TITLE
[FEATURE] chose color of tile

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#52]
When a device is on the icon background turns green. When it's off it turns red.

Would be great that the whole tile changes color maybe an option to turn this on or off so people can use it if they want. 

What also could is the option to chose the tile color by behavior. For example. Airco heating orange.
Airco cooling blue.
Airco off red.

**Comment by StevenRenders** [comment]
And when choosing a color also the potion tot make it (semi) transparant.

**Comment by mennovanhout** [comment]
This is done in v0.4.6

Transparant is not there, sadly it's also not supported by homeys color picker.
