### ISSUE TITLE
[BUG] Icon sensors gone

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#53]
**Describe the bug**
The icons are gone from my sensors

**Expected behavior**
Icons back

**Screenshots**
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/32e3a363-352c-4e46-ba84-29fe017e8aca)

**Using information (please complete the following information):**
 - Browser Chrome, Dashboard v0.2.0

**Homey device**
 - Device: Homey pro 2023

**Additional context**
The icons in the web are gone. in the android app v0.1.1 they are ok

**Comment by mennovanhout** [comment]
When did you add those devices?

**Comment by StaffordBully** [comment]
A few time ago.But when I saw, I deleted and added them again and still no icon. So few min later I made this bug request Vriendelijke groeten,Akkermans Bart+32 487 690 408
-------- Oorspronkelijk bericht --------Van: Menno van Hout ***@***.***> Datum: 2/10/2023  20:14  (GMT+01:00) Aan: mennovanhout/flutter-hdashboards-issues ***@***.***> Cc: StaffordBully ***@***.***>, Author ***@***.***> Onderwerp: Re: [mennovanhout/flutter-hdashboards-issues] [BUG] Icon sensors gone (Issue #53) 
When did you add those devices?
