### ISSUE TITLE
[FEATURE] Device of type "Smart Presence" does not show status

### ISSUE THREAD

**Issue by jeesnl** [mennovanhout/flutter-hdashboards-issues#55]
**Describe the bug**
When there is a device for presence of the "Smart Presence" app this device does not show the status in HDashboards.

**To Reproduce**
Create a Smart Presence Device
Add it to HDashboards 
It does not show any of the statuses.

**Comment by mennovanhout** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/50e94c12-f1a4-40fb-bec1-85fa488356dc)

**Comment by jeesnl** [comment]
This one came back at one of the latest updates.

**Comment by jeesnl** [comment]
During testing of the user function i found out that the color off the icon is now changing reflecting the presence, but the tile stays grey. Can you change the color of the tile also. That also was the case in the previous version. 

Thanks in advance.

**Comment by mennovanhout** [comment]
Fixed in 0,3,0

**Comment by jeesnl** [comment]
The tiles are still grey when they are on.

**Comment by mennovanhout** [comment]
you don't have the fix yet ;P
