### ISSUE TITLE
[BUG] Device states dont update after long inactivity

### ISSUE THREAD

**Issue by freekiebakhuis** [mennovanhout/flutter-hdashboards-issues#56]
No feedback op buttons ipad app

after a night no feedback buttons ipad app

**Comment by mennovanhout** [comment]
You mean that after a night the buttons don't auto update when a device state chances?

**Comment by freekiebakhuis** [comment]
Yes thats what i mean

**Comment by freekiebakhuis** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/99759489/6f68e866-6e31-4f6b-8578-5565d1f7b334)

Problem is the sleeping mode, see clock ipad and clock tile

**Comment by freekiebakhuis** [comment]
Same on iphone

**Comment by mennovanhout** [comment]
thanks will look into it soon!

**Comment by mennovanhout** [comment]
Will be done in v0.2.5

**Comment by freekiebakhuis** [comment]
Does not work fine yet![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/99759489/3dd063e1-67ab-4837-a25d-897e5de8c831)

**Comment by freekiebakhuis** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/99759489/8fd556f1-9a26-4fe1-b5d8-1c6781c13275)

See clock on iphone and analog vlock do not match after lock en unlock iphone
