### ISSUE TITLE
[BUG] Problem when rgb dims

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#59]
**Describe the bug**
When I dim my rgb lights to min the tile gets black. So then I don't see my light color anymore

**Expected behavior**
What the dimlevel is, I want always see my light color.

**Screenshots**
![image0.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/90a9e0e7-b28e-4e67-8834-95ee3c84b2af)

![image0-1.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/59df44e6-bce9-4601-8dd8-f73505591d74)

**Using information (please complete the following information):**
 - OS: Android
 - Browser Chrome
 - Version all

**Homey device**
 - Device: Homey 2023

**Comment by mennovanhout** [comment]
Well it actually is your light color, how would you distinqish dark purple and purple?

**Comment by StaffordBully** [comment]
This is an example. It's the same with every color. Look this is yellow.

![SmartSelect_20231010_205756.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/e98bc5b0-4692-4b6e-9177-a6e4b9ca781c)

![SmartSelect_20231010_205741.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/ee822573-5aba-43a8-9ee7-91e80be0d73d)

**Comment by mennovanhout** [comment]
yes which makes sense, How else should i display that the brightness is turned down xD?

**Comment by StaffordBully** [comment]
Is it not an option that the color not changed but just visual like the slider.
