### ISSUE TITLE
[FEATURE] Overridden icons

### ISSUE THREAD

**Issue by mennovanhout** [mennovanhout/flutter-hdashboards-issues#60]
Right now when you add an device it can use the original icon of the Homey app. But it would be nice if it checks for icon overides and if so take those instead.

**Comment by mennovanhout** [comment]
Seems to be impossible since Homey doesn't send them as SVG but with a name...

**Comment by ronaldsomers** [comment]
To bad.

**Comment by mennovanhout** [comment]
If it ever will be possible im gonna implement it :D
