### ISSUE TITLE
[FEATURE] Thermostat behavior

### ISSUE THREAD

**Issue by powermarcel10** [mennovanhout/flutter-hdashboards-issues#61]
Hi, I have 2 feature requests regarding themostats: 

As suggested before I like a thermostat like this wich is much easier to control instead of pressing 2 verry small buttons (+/-) like it is now;

![thermostat_card](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/2340835/3a326b93-7ada-4c68-94b7-af3a5c430c3d)

Also, my airco is marked as a thermostat, wich is fine, but I cannot turn it on/off using the current card..

**Comment by StaffordBully** [comment]
Same here with my airco, can't turn on/off.
The indicator "Blue cirkel" does't change when thermostat mode is changed.

**Comment by mennovanhout** [comment]
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/21b8d23f-9f27-40a3-8a53-5fd23c36a70a)
