### ISSUE TITLE
[FEATURE] Icons size and color

### ISSUE THREAD

**Issue by powermarcel10** [mennovanhout/flutter-hdashboards-issues#62]
Hi,

I have some requests regarding icons:

I like to see the icons a bit bigger as they are now
Option to choose your own color for icons
Option to choose icons for flowcards
Option to add your own icons

Cheers,
Marcel

**Comment by mennovanhout** [comment]
Thanks marcel!

**Comment by mennovanhout** [comment]
Option to choose your own color for icons -> will be coming in theme editor
Option to choose icons for flowcards -> ADDED will be there in next update 0.2.7
Option to add your own icons -> I agree will work on an SVG system
Will work on available size.

**Comment by mennovanhout** [comment]
I am closing this for now:
I am always trying to increase size where possible due the fact that cards can be resized this sometimes works and sometimes doesn't this will be on my list to always look for ui improvements.
