### ISSUE TITLE
[BUG] time out na werken in andere app

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#63]
**Describe the bug**
Als de app naar de achtergrond gaat en weer naar de voorgrond verschijnt er een time-out.

**To Reproduce**
Open HDashboards app, open een Dashboard, open de Homey app of een andere app, ga terug naar HDaschboards app.

**Expected behavior**
Ik verwacht het dashboard te zien.

**Screenshots**
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/5a1db184-d95d-481b-b63f-a0e3ff07d7e9)

**Using information (please complete the following information):**
 - OS: iOS 17.0.3
 - Browser: n.v.t.
 - Version: n.v.t.

**Homey device**
 - Device: Homey Pro 2023

**Additional context**

**Comment by ronaldsomers** [comment]
Ook in de browser Safari gebeurt hetzelfde.

**Comment by mennovanhout** [comment]
Thanks ga er meteen naar kijken

**Comment by ronaldsomers** [comment]
Hoi Marcel,helaas, na update toch niet opgelost.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/147695384/a76ed3c1-aceb-4eff-a382-c001f17d32a5)

**Comment by ronaldsomers** [comment]
Ben nog even aan ‘t testen maar ook verversen bij een openstaand scherm lijkt nog niet opgelost.
Wanneer ik op mijn IPad een dashboard aanpas dan verschijnt de aanpassing pas op een mijn Wall iPad waar dat dashboard open staat pas wanneer ik van dashboard wissel op de Wall ipad.
Ik had begrepen in de nieuwe versie elke 5 min verversen.

**Comment by mennovanhout** [comment]
Een dashboard aanpassen op apparaat x doet nu geen wijzigingen op andere apparaten. Om de 5 minuten ververst hij de bestaande kaarten. Wel een goed punt wat ik nog ga oppakken!

**Comment by ronaldsomers** [comment]
Duidelijk wat betreft aanpassen op X en andere apparaten.

Het verversen op bestaand (openstaande?) kaarten gaat niet goed.
Op mijn mijn wallmounted iPad houdt ie er op gegeven moment mee op.
Moet zelfs de app afsluiten en opnieuw opstarten.

**Comment by mennovanhout** [comment]
Update de app naar de aller laatste versie via de playstore!

**Comment by ronaldsomers** [comment]
> Update de app naar de aller laatste versie via de appstore!
thanks

Zal ik doen, had vandaag al een keer gedaan, zie nu idd 0.2.6
