### ISSUE TITLE
[FEATURE] Timeline month in english

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#66]
**Is your feature request related to a problem? Please describe.**
the month in the timeline is in english

**Describe the solution you'd like**

**Describe alternatives you've considered**
possible to use language from homey to show months

**Additional context**

**Comment by mennovanhout** [comment]
Whole HDashboards is currently in english i would like to remain the app language. I will add support for other languages at some point.
