### ISSUE TITLE
[BUG] Verversen stopt na bepaalde tijd

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#68]
**Describe the bug**
Als de app open blijft staan wordt op een gegeven moment het scherm niet meer ververst.
1 stap terug naar overzicht met dashboard helpt soms, anders app afsluiten en opnieuw opstarten.

**To Reproduce**
1. Go to app opstarten
2. Click on dashboard openen en open laten staan.

**Expected behavior**
Dat het geopende dashboard blijft verversen

**Screenshots**

**Using information (please complete the following information):**
 - OS: iOS 17.0.3
 - Browser nvt
 - Version nvt

**Homey device**
 - Device: Homey pro 2023

**Comment by mennovanhout** [comment]
Dankje! I might have a solution for this I'll implement it asap

**Comment by mennovanhout** [comment]
Fixed in upcoming version v0.2.5

**Comment by ronaldsomers** [comment]
> Fixed in upcoming version v0.2.5

Helaas niet opgelost, zie comment issue #63
