### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by freekiebakhuis** [mennovanhout/flutter-hdashboards-issues#69]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Using information (please complete the following information):**
 - OS: [e.g. iOS, Android, Windows]
 - Version [e.g. Android app v0.0.7, web version v0.0.7]

**Homey device**
 - Device: [e.g. Homey pro 2023, Homey cloud]

**Additional context**
 

Still no update tiles on iphone unlock

**Comment by mennovanhout** [comment]
Working on it!!!

**Comment by freekiebakhuis** [comment]
I did install it this morning, for so far every thing works fine (except clock but that is in future release)
Did bot have much time to test
Thanks for the good work, i really enjoy the dashboard

**Comment by mennovanhout** [comment]
Thanks @freekiebakhuis will work on the clock :D other than that it should work stable now. Thanks for bringing this to my attention.

**Comment by mennovanhout** [comment]
Clocks fixed in 0.2.7
