### ISSUE TITLE
[BUG] toevoegen Aqara bewegingssensoren

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#70]
Het lukt niet om een bewegingssensor toe te voegen van Aqara.

Toevoegen device
Kies Aqara bewegingssensor
Voeg toe

Verwacht de sensor te zien

 Homey pro 2023, Homey 

Betreft sensor: Lumi.sensor_motion.aq2

**Comment by mennovanhout** [comment]
Het apparaat staat helemaal niet tussen de devices list?

**Comment by ronaldsomers** [comment]
Staat er wel tussen, na drukken “add” verschijnt deze niet op ‘t dashboard.

**Comment by mennovanhout** [comment]
Hoe heet het apparaat? ga ik even testen.

**Comment by ronaldsomers** [comment]
Lumi.sensor_motion.aq2

**Comment by mennovanhout** [comment]
thanks ronals ga ik voor je fixen :D

**Comment by mennovanhout** [comment]
Ronald, heb je voor mij de Homey naam de naam waarmee hij in de "devices" list staat tijdens het toevoegen.
Vindt je het daarnaast oke als ik lokaal heel kort met je homey verbind om te testen/kijken waar het mis gata zodat ik het kan oplossen?

**Comment by ronaldsomers** [comment]
Hoi Menno,
Naam sensor in devices is: 0.11.02 GA
Kort verbinden is oke.

**Comment by ronaldsomers** [comment]
Hoi Menno,Met naam van Homey bedoel je dan het cloud ID?Deze slinger ik dan dus gewoon even naar je toe, hmmm, dat vind ik nogal.Heb je zelf geen Aqara sensor(en)?Met vriendelijke groet, Ronald Somers Op 22 okt 2023 om 10:27 heeft Menno van Hout ***@***.***> het volgende geschreven:﻿
Ronald, heb je voor mij de Homey naam de naam waarmee hij in de "devices" list staat tijdens het toevoegen.
Vindt je het daarnaast oke als ik lokaal heel kort met je homey verbind om te testen/kijken waar het mis gata zodat ik het kan oplossen?

**Comment by mennovanhout** [comment]
Dag Ronald,

Ik heb de fout gevonden en opgelost! Vanaf nu kan het wel. het SVG icoontje was te groot.

**Comment by ronaldsomers** [comment]
Thanks, het is gelukt!
