### ISSUE TITLE
[BUG] Simulate other device widths from browser

### ISSUE THREAD

**Issue by ronaldsomers** [mennovanhout/flutter-hdashboards-issues#73]
Het verplaatsen van een tegel op iPad A wordt niet meegenomen op iPad B
IPad B HDasboard afgesloten en opnieuw opgestart, als ook daarna de iPad opnieuw opgestart, helaas, tegel komt niet op de nieuwe plek.
IPad A, waar ik de tegel verplaatst heb blijft op de nieuwe plek staan.

Ook wanneer HDash naar achtergrond gaat en weer opgeroepen wordt verschijnt er een time-out.

**Comment by ronaldsomers** [comment]
Het zijn inderdaad verschillende iPads qua jaar en type.

**Comment by mennovanhout** [comment]
Dan komt het door het verschillende scherm grootte ben bang dat dat gedrag gewenst is.
Vooral zodat mensen een dashboard kunnen hergebruiken op meerdere apparaten.

**Comment by mennovanhout** [comment]
ik ga in browsers ondersteuning maken voor het speciaal designen voor verschillende formaten.

**Comment by ronaldsomers** [comment]
Top Menno, als ik kan helpen door te testen laat maar weten!

**Comment by mennovanhout** [comment]
Weet dat het lang duurt, user management etc kwam voor qua importance nu bezig met de eerste multi tiles daarna staat dit op de planning!

**Comment by mennovanhout** [comment]
Cancelled and replaced by the new max width setting:

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/f0a7e52e-4c8a-4a2f-a41c-67ccf60248ed)
Choose the same max width as your desired tablet and both will use this layout now

**Comment by ronaldsomers** [comment]
Welke waarde dient er ingevuld te worden?

**Comment by ronaldsomers** [comment]
Thanks, dat wilde ik weten!
Dan geldt dat dus ook voor mijn iPads?
Je kent mijn iPads, de grootste heeft 10 op de x as en de kleine 11.
Wanneer ik dan op de kleine 10 instel werkt dat hetzelfde, neem ik aan.

**Comment by mennovanhout** [comment]
Yes dan raad ik je aan om alle devices op 10 te zetten en zou je helemaal happy moeten zijn!
