### ISSUE TITLE
[FEATURE] resize overview dashboard 

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Possibility to resize overview dashboards 

**Describe alternatives you've considered**
Tiles are big on android phone. Like it as we can make it 1/4 

**Additional context**
![Screenshot_20231023_085817.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/4de95e5b-9130-42d2-be50-45bc1e746057)

**Comment by mennovanhout** [comment]
Done in 0.2.8
