### ISSUE TITLE
[BUG] Edit in dark mode: grid is very hard to see, 

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#75]
When editing in Dark mode, the grid lines are very hard to see, and sometimes in low light conditions (lowe brilliance than most people (don't want to have laser eyes) I am not able to see them. Advices to make the grid lines more white or whiter and a bit thicker.

If I look at light theme, then the grid can also have a bit more contrast, but it is better than in dark mode.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/20a155c5-9b94-4121-b786-d80a8ece97d8)

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/e8f8c9ff-d627-486d-a3c7-ac524d4c4275)

**Comment by mennovanhout** [comment]
sure will add more contrast imedietly for next deployment!

**Comment by mennovanhout** [comment]
done in 0.2.8
