### ISSUE TITLE
[BUG] shows only 1 battery

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#78]
**Describe the bug**
I have a virtual device where i connected 2 devices, add the option to show battery status.
when i long press i only see one battery, the one with the most %.

**Expected behavior**
Show both/all battery status when long press

**Comment by mennovanhout** [comment]
Can you tell me your devcie name?

**Comment by StaffordBully** [comment]
Gordijnen Bureau & Gordijnen Keuken

**Comment by mennovanhout** [comment]
Solved in upcoming update

**Comment by StaffordBully** [comment]
possible to add name like in homey under the batteries? 
for the rest Great Job

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/a2743827-4430-4465-984e-73977e7b4764)

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/03d1428b-cb90-4ba2-9ae5-fa9d09031574)
