### ISSUE TITLE
[BUG] Homewizard Wallplug

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#80]
**Describe the bug**
When i add homewizard wallplug than its get the wrong icon,
on/off react not as on/off plug but as on/off lock on wallplug

**Expected behavior**
on/off the wallplug it self by clicking it

**Screenshots**
Add, see icon
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/ba312d76-e802-4989-8ce4-744e2293a8b4)
Tile icon. 
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/15155dea-8770-4ca6-bd06-898ec68d9c96)
Tile in homey where you see the on/off lock option
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/373bebbb-28fe-43fb-b904-96074bb64ad1)

**Comment by mennovanhout** [comment]
jezus wallplug with locks XD?

**Comment by mennovanhout** [comment]
Solved in 0.2.8+11
