### ISSUE TITLE
[FEATURE] Alarm tile

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#81]
**Describe the solution you'd like**
A tile for alarm where the icon changes by status.

**Additional context**
![SmartSelect_20231029_204514.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/cfe18437-f4fb-44ef-954b-57e68bdfecf4)

**Comment by mennovanhout** [comment]
Cancelled, but can be used by setting colors via companion app.
