### ISSUE TITLE
[BUG] letters flatten from bottom

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#82]
**Describe the bug**
When tile is 1x1 (on phone) the letters disappear from the bottom

**Screenshots**
Stand by
![SmartSelect_20231029_204732.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/d76d6de1-2afd-4289-a314-5f18926888ba)

Ontgrendeld
![SmartSelect_20231029_204804.jpg](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/250a67cc-08fb-40f1-bd75-1f51b51d3d10)

**Using information (please complete the following information):**
 - OS: [, Android, Windows]
 - Browser [chrome]
 - Version  Android app v0.2.8+11, web version v0.2.8+11]

**Comment by mennovanhout** [comment]
You mean that the bottom of the letters is cutoff?

**Comment by StaffordBully** [comment]
Yes indeedVriendelijke groeten,Akkermans Bart+32 487 690 408
-------- Oorspronkelijk bericht --------Van: Menno van Hout ***@***.***> Datum: 29/10/2023  21:00  (GMT+01:00) Aan: mennovanhout/flutter-hdashboards-issues ***@***.***> Cc: StaffordBully ***@***.***>, Author ***@***.***> Onderwerp: Re: [mennovanhout/flutter-hdashboards-issues] [BUG] letters flatten from bottom (Issue #82) 
You mean that the bottom of the letters is cutoff?

**Comment by mennovanhout** [comment]
Done in next update
