### ISSUE TITLE
[BUG] switches can't turn on/off

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#83]
**Describe the bug**
Switches can't turn on/off by clicking it.
The new color layout also doesn't work on them.

**Expected behavior**
When clicking on them turn on/off switch. Option for longpres when it's a bubble switch. when longpress chose button 1 or 2.

**Comment by mennovanhout** [comment]
Share a device name with me. And if I can test with it?

**Comment by StaffordBully** [comment]
Walli switch keuken, that's a single 
Walli switch bureau, that's a double
You may test, no problem

**Comment by mennovanhout** [comment]
Done in next update
