### ISSUE TITLE
[BUG] Pushbutton doesn't work

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#84]
**Describe the bug**
When i have a virtual device with pushbutton and click on the tile nothing happens

**Expected behavior**
when i push the tile it react as a pushbutton

**Using information (please complete the following information):**
 - OS: [Android]
 - Browser [chromei]
 - Version [Android app v0.2.8+11 web version v0.2.8+11]

**Homey device**
 - Device: [Homey pro 2023]

**Comment by mennovanhout** [comment]
Done in next update
