### ISSUE TITLE
[FEATURE] Button popup screen

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#85]
**Is your feature request related to a problem? Please describe.**
When i have a virtual device as button but with (saturation, hue and dim) and i long press the popup shows color first.

**Describe the solution you'd like**
When its a button is it possible to show capabilities first? because color is used for tile and no need to change that.
maybe when its a button hide color and dim?

**Comment by mennovanhout** [comment]
Done in next update
