### ISSUE TITLE
[FEATURE] Flows is limited in options

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#86]
**Is your feature request related to a problem? Please describe.**
When a flow is disabled in homey i can't add them to Hdashbords

**Describe the solution you'd like**
Add flows enables or disabled
Color icon is now green, use that for enabled flows and make red for disabled flows?
Longpress to enable and disable flow?

**Comment by mennovanhout** [comment]
I've decided that enabling / disabling flows is not something a dashboard tool should be doing for now.
