### ISSUE TITLE
[BUG] airco on/off

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#88]
**Describe the bug**
Airco can't turn on/off by clicking tile

**Expected behavior**
When clicking tile turn airco on/off

**Comment by mennovanhout** [comment]
Can you check if this is resolved?

**Comment by StaffordBully** [comment]
Still not working

**Comment by mennovanhout** [comment]
still in v0.3.0?

**Comment by StaffordBully** [comment]
Now they can be switched on/off. 
But no visual if the device is on/off

**Comment by mennovanhout** [comment]
done in v0.3.2

**Comment by StaffordBully** [comment]
When no label selected theirs no visual if the device is on/off

**Comment by mennovanhout** [comment]
but the tab does work?

**Comment by StaffordBully** [comment]
Yes on/off by tab works

**Comment by mennovanhout** [comment]
Can you re-check in the latest version? should've added support for quick touch in the device icon. I guess you are talking about that visual.

**Comment by StaffordBully** [comment]
Visual is okay. Clicking is okay.
