### ISSUE TITLE
[FEATURE] Multi Push buttons

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#89]
**Is your feature request related to a problem? Please describe.**
multi push buttons doesn't work, only multi on/off

**Describe the solution you'd like**
long press showing multi push buttons

**Comment by mennovanhout** [comment]
Done in next update:
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/bfda2b2a-d906-4a44-846b-537edf976fcc)
