### ISSUE TITLE
[FEATURE] Default dashboard to open

### ISSUE THREAD

**Issue by markmastop** [mennovanhout/flutter-hdashboards-issues#9]
The direct URL to open the dashboard is working super.

I would like to be able to set a default dashboard to open automatically when logging in or using the magic link.

In this way you can auto start a tablet with the "default" dashboard or use a google cast to start a dashboard on a TV or tablet.

Other option would be to have a magic link per dashboard.

**Comment by mennovanhout** [comment]
Thanks will keep it around.
