### ISSUE TITLE
[FEATURE] Slider device capabilities

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#90]
**Is your feature request related to a problem? Please describe.**
When adding a slider in device capabilities the dashboard doesn't recognize it.
Only when set as dim, but that's not the way because dim is set as 0.00 and if you want the slider set at 20 then dim is set to 1

**Describe the solution you'd like**
Add slider to tile so it can be used for example min.
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/5f8419b9-d76e-4c53-8e21-7e13f57f256c)

**Comment by mennovanhout** [comment]
done in v0.0.3
