### ISSUE TITLE
[BUG] Image URL does not work on local http  url

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#91]
**Describe the bug**
I have a local URL to a local Grafana instance and the URL works in a browser.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install  a local Grafana instance and create a dashboard
2. Activate anonymous mode
3. Take a url from a dashboard  http://192.168.10.2:13000/d/hTj-zA4Sz/quooker-information?orgId=1&kiosk
4.  Add Image URL to HDashboard 

**Expected behaviour**
A clear image of the webpage

**Screenshots**
Now:
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/1efb914e-c941-4682-9f76-9e4d7497697f)

Expected image (taken from a browser):
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/7f07018b-b175-4f11-bae1-c403108a7182)

[Grafana page source.txt](https://github.com/mennovanhout/flutter-hdashboards-issues/files/13355422/Grafana.page.source.txt)

**Comment by mennovanhout** [comment]
Isn't it caused by the fact that the url is not an image? but a webpage?

**Comment by MP-ICT-Diensten** [comment]
Yes, probably.  Buienradar is also not directly an image?    I thought that you already created images from a site.

**Comment by mennovanhout** [comment]
Haha no buienradar does return an image

**Comment by mennovanhout** [comment]
You could check this: https://grafana.com/docs/grafana/latest/dashboards/share-dashboards-panels/#use-direct-link
Grafana can create image urls
