### ISSUE TITLE
[BUG] Dashboard Tile name

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#92]
**Describe the bug**
When you add a dashboard tile the icon and name is shown.  But when you set it 1x1 tile it only show the name and is scrolling or name is broken by .... 

**Expected behavior**
Is it not an option to choose between icon or name.  Than when it's small I can use icon and have no scrolling or broken text

**Screenshots**
![image0](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/144690805/c7d98e30-b1c9-4e2b-b436-984917751b1f)

**Using information (please complete the following information):**
 - OS: [Android]
 - Version [Android app v0.3.1+14]

**Comment by mennovanhout** [comment]
Done in v0.3.2

**Comment by StaffordBully** [comment]
Still the same.

**Comment by mennovanhout** [comment]
v0.3.3 icons will be removed on small size and only text will be displayed.
I've done some test but the tile just becomes to small to even identify what kind of icon you are seeing
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/c2881f7a-e16f-4599-92b2-493c67adb153)
