### ISSUE TITLE
[FEATURE] More/better functionality when it comes to sharing dashboards

### ISSUE THREAD

**Issue by marium0505** [mennovanhout/flutter-hdashboards-issues#93]
**Is your feature request related to a problem? Please describe.**
Seems like this one is much better than SharpTools, especially in terms of not having to pick every single item I want from Homey (note: property and not device) and into HDashboards. I also like that stuff shows up in HDashboards filtered by type (so devices in one, flows in another etc). I also like that you can search, making it a lot easier to find what you're looking for. I haven't tested with adding our summer house yet though, but I hope stuff is filtered by home, and that not all flows/devices are thrown together without any kind of filtering based on home (I have a lot of devices in both, a lot also custom).
One thing both seem to be missing though is better sharing features. I would love to share stuff with people without them having to create an account somewhere, if they have to do that they can just as well get a Homey account. 

**Describe the solution you'd like**

One option I would love to see is the ability to allow access to dashboards from IP addresses etc, and generally more ways to share dashboard with others that doesn't require them to have a HDashboards account.

**Comment by mennovanhout** [comment]
What I would suggest for safety regards is:
Email addresses don't have to exist for sub accounts in hdashboards.
Create an account with a choosen email adress and use the authenticated URL. Than you achieve exactly what you want.
