### ISSUE TITLE
[FEATURE] Add supprot for reversed blinds

### ISSUE THREAD

**Issue by mennovanhout** [mennovanhout/flutter-hdashboards-issues#95]
Guten Tag

Besten Dank für die tolle App, die ich bereits ausgiebig teste.
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/c844fbbc-bb05-40e4-a030-6da5ff0985d6)
Bei den Lamellenstoren und den Sonnenstoren (Somfy) habe ich das Problem, dass die Anzeige / resp. Position umgekehrt werden muss.

Bei einigen zeigt die Position 100 und ist oben, bei anderen 0 und ist oben. Hilfreich wäre, wenn wie im Homey Somfy die Anzeige reverse angezeigt werden könnte:

 
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/f8da8400-5cc8-4f51-929c-a24117846f0a)
3 Ost ist aktuell oben!

 

Danke für Ihre Hilfe

**Comment by mennovanhout** [comment]
Fixed in upcoming version 0.3.2

**Comment by MP-ICT-Diensten** [comment]
Question, did you only add blinds?

because homey also knows Curtains, Sunshade and Window Coverings, I uses Sunshade on virtual devices and groups. And I have shelly rollers fo sunscreens, all not in reverse order yet.

**Comment by mennovanhout** [comment]
I think it will automatically work for all of those.

**Comment by MP-ICT-Diensten** [comment]
I tried, but it doesnt,  have sunscreen and windowconverings  the sunscreen is a <group>

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/2c67991d-fdfc-48bf-9dc6-8c04e9e529df)

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/28575285/f904270f-7e80-41d8-baf1-485b86ea2bb2)
