### ISSUE TITLE
[BUG] open url timeline

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#97]
**Describe the bug**
When there's a url in the timeline it's blue and when you move your mouse over it the mouse change to a hand whats indicated as a click able link. But when you click noting happens

**Expected behavior**
When there's a url in timeline open by clicking link

**Comment by mennovanhout** [comment]
Done in v0.3.3

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/1c1a0912-4d5f-4f07-b952-08232e7d08b7)
