### ISSUE TITLE
[FEATURE] link to this page (issues) from About or changelog page

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [mennovanhout/flutter-hdashboards-issues#99]
Link in dashboard it self to these issue page, so that if you have an issue you can reach more easely this page with open and closed issues.

especially when using a tablet or phone, it is hard to keep all kinds of urls easy remebered.

**Comment by mennovanhout** [comment]
I agree I will do this in the next update.

Thank you for all the great feedback over the past weeks

**Comment by mennovanhout** [comment]
Done in upcoming v0.3.3
![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/26040589/6abe10a5-dcee-40d9-96c1-e289187aeca0)
